# SCIP defines for character, string, and numeric constants
export TRUE, FALSE, _SCIP_VERSION, _SCIP_SUBVERSION, _SCIP_COPYRIGHT, _SCIP_VARTYPE_BINARY_CHAR, _SCIP_VARTYPE_INTEGER_CHAR, _SCIP_VARTYPE_IMPLINT_CHAR, _SCIP_VARTYPE_CONTINUOUS_CHAR, _SCIP_LONGINT_FORMAT, _SCIP_REAL_FORMAT, _SCIP_MAXSTRLEN, _SCIP_HASHSIZE_PARAMS, _SCIP_HASHSIZE_NAMES, _SCIP_HASHSIZE_CUTPOOLS, _SCIP_HASHSIZE_CLIQUES, _SCIP_HASHSIZE_NAMES_SMALL, _SCIP_HASHSIZE_CUTPOOLS_SMALL, _SCIP_HASHSIZE_CLIQUES_SMALL, _SCIP_HASHSIZE_VBC, _SCIP_EXPR_DEGREEINFINITY, ARTIFICIALVARNAMEPREFIX
const TRUE = 1
const FALSE = 0
const _SCIP_VERSION = 311
const _SCIP_SUBVERSION = 0
const _SCIP_COPYRIGHT = "Copyright (c) 2002-2014 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)"
const _SCIP_VARTYPE_BINARY_CHAR = 'B'
const _SCIP_VARTYPE_INTEGER_CHAR = 'I'
const _SCIP_VARTYPE_IMPLINT_CHAR = 'M'
const _SCIP_VARTYPE_CONTINUOUS_CHAR = 'C'
const _SCIP_LONGINT_FORMAT = "lld"
const _SCIP_REAL_FORMAT = "lf"
const _SCIP_MAXSTRLEN = 1024
const _SCIP_HASHSIZE_PARAMS = 4099
const _SCIP_HASHSIZE_NAMES = 131101
const _SCIP_HASHSIZE_CUTPOOLS = 131101
const _SCIP_HASHSIZE_CLIQUES = 131101
const _SCIP_HASHSIZE_NAMES_SMALL = 8011
const _SCIP_HASHSIZE_CUTPOOLS_SMALL = 8011
const _SCIP_HASHSIZE_CLIQUES_SMALL = 8011
const _SCIP_HASHSIZE_VBC = 131101
const _SCIP_EXPR_DEGREEINFINITY = 65535
const ARTIFICIALVARNAMEPREFIX = "andresultant_"

# SCIP defines for known C types and pointers to SCIP structs.
export _SCIP_PRICERDATA, _SCIP_PRICER, _SCIP_Real, _SCIP_Bool, _SCIP_CLIQUE, _SCIP_VAR, _SCIP, _SCIP_CONS, _SCIP_PRESOLDATA, _SCIP_PRESOL, _SCIP_SOL, _SCIP_PROFILE, _SCIP_ROW, _SCIP_EVENTHDLR, _SCIP_EVENTHDLRDATA, _SCIP_EVENTTYPE, _SCIP_EVENT, _SCIP_NODE, _SCIP_COL, _SCIP_MESSAGEHDLR, _SCIP_HASHMAP, _SCIP_CONSHDLR, _SCIP_PARAM, _SCIP_READER, _SCIP_READERDATA, _SCIP_CONFLICTHDLR, _SCIP_RELAX, _SCIP_SEPA, _SCIP_PROP, _SCIP_HEUR, _SCIP_NODESEL, _SCIP_BRANCHRULE, _SCIP_BRANCHRULEDATA, _SCIP_DISP, _SCIP_NLPI, _SCIP_DIALOG, _SCIP_PROBDATA, _SCIP_BDCHGIDX, _SCIP_CONSDATA, _SCIP_PROPTIMING, _SCIP_REALARRAY, _SCIP_LPI, _SCIP_NLROW, _SCIP_NLPSTATISTICS, _SCIP_NLPIPROBLEM, _SCIP_QUADELEM, _SCIP_EXPRTREE, _SCIP_INTERVAL, _SCIP_CUT, _SCIP_CUTPOOL, _SCIP_EVENTDATA, _SCIP_CLOCK, _SCIP_INTARRAY, _SCIP_BOOLARRAY, _SCIP_PTRARRAY, _SCIP_HEURDATA, _SCIP_HEURTIMING, _SCIP_CONFLICTHDLRDATA, _SCIP_EXPRGRAPHNODE, _SCIP_EXPRGRAPH, _SCIP_CONSHDLRDATA, _SCIP_PROPDATA, _SCIP_SPARSESOL, _SCIP_QUEUE, _SCIP_PQUEUE, _SCIP_HASHTABLE, _SCIP_HASHMAPLIST, _SCIP_RESOURCEACTIVITY, _SCIP_DIGRAPH, _SCIP_BT, _SCIP_BTNODE, _SCIP_DISPDATA, _SCIP_HISTORY, _SCIP_VALUEHISTORY, _SCIP_NODESELDATA, _SCIP_BASESTAT, _SCIP_EXPR, _SCIP_EXPRDATA_MONOMIAL, _SCIP_EXPRINTDATA, _SCIP_SEPADATA, _SCIP_QUADVARTERM, _SCIP_BILINTERM, _SCIP_MESSAGEHDLRDATA, _SCIP_PARAMDATA, _SCIP_DOMCHG, _SCIP_DIALOGHDLR, _SCIP_DIALOGDATA, _SCIP_VARDATA, _SCIP_HOLELIST, _SCIP_BDCHGINFO, _SCIP_BOUNDCHG, _SCIP_RELAXDATA
abstract SCIPType
export SCIPType
type _SCIP_PRICERDATA <: SCIPType end
type _SCIP_PRICER <: SCIPType end
typealias _SCIP_Real Float64
typealias _SCIP_Bool Uint
type _SCIP_CLIQUE <: SCIPType end
type _SCIP_VAR <: SCIPType end
type _SCIP <: SCIPType end
type _SCIP_CONS <: SCIPType end
type _SCIP_PRESOLDATA <: SCIPType end
type _SCIP_PRESOL <: SCIPType end
type _SCIP_SOL <: SCIPType end
type _SCIP_PROFILE <: SCIPType end
type _SCIP_ROW <: SCIPType end
type _SCIP_EVENTHDLR <: SCIPType end
type _SCIP_EVENTHDLRDATA <: SCIPType end
type _SCIP_EVENTTYPE <: SCIPType end
type _SCIP_EVENT <: SCIPType end
type _SCIP_NODE <: SCIPType end
type _SCIP_COL <: SCIPType end
type _SCIP_MESSAGEHDLR <: SCIPType end
type _SCIP_HASHMAP <: SCIPType end
type _SCIP_CONSHDLR <: SCIPType end
type _SCIP_PARAM <: SCIPType end
type _SCIP_READER <: SCIPType end
type _SCIP_READERDATA <: SCIPType end
type _SCIP_CONFLICTHDLR <: SCIPType end
type _SCIP_RELAX <: SCIPType end
type _SCIP_SEPA <: SCIPType end
type _SCIP_PROP <: SCIPType end
type _SCIP_HEUR <: SCIPType end
type _SCIP_NODESEL <: SCIPType end
type _SCIP_BRANCHRULE <: SCIPType end
type _SCIP_BRANCHRULEDATA <: SCIPType end
type _SCIP_DISP <: SCIPType end
type _SCIP_NLPI <: SCIPType end
type _SCIP_DIALOG <: SCIPType end
type _SCIP_PROBDATA <: SCIPType end
type _SCIP_BDCHGIDX <: SCIPType end
type _SCIP_CONSDATA <: SCIPType end
type _SCIP_PROPTIMING <: SCIPType end
type _SCIP_REALARRAY <: SCIPType end
type _SCIP_LPI <: SCIPType end
type _SCIP_NLROW <: SCIPType end
type _SCIP_NLPSTATISTICS <: SCIPType end
type _SCIP_NLPIPROBLEM <: SCIPType end
type _SCIP_QUADELEM <: SCIPType end
type _SCIP_EXPRTREE <: SCIPType end
type _SCIP_INTERVAL <: SCIPType end
type _SCIP_CUT <: SCIPType end
type _SCIP_CUTPOOL <: SCIPType end
type _SCIP_EVENTDATA <: SCIPType end
type _SCIP_CLOCK <: SCIPType end
type _SCIP_INTARRAY <: SCIPType end
type _SCIP_BOOLARRAY <: SCIPType end
type _SCIP_PTRARRAY <: SCIPType end
type _SCIP_HEURDATA <: SCIPType end
type _SCIP_HEURTIMING <: SCIPType end
type _SCIP_CONFLICTHDLRDATA <: SCIPType end
type _SCIP_EXPRGRAPHNODE <: SCIPType end
type _SCIP_EXPRGRAPH <: SCIPType end
type _SCIP_CONSHDLRDATA <: SCIPType end
type _SCIP_PROPDATA <: SCIPType end
type _SCIP_SPARSESOL <: SCIPType end
type _SCIP_QUEUE <: SCIPType end
type _SCIP_PQUEUE <: SCIPType end
type _SCIP_HASHTABLE <: SCIPType end
type _SCIP_HASHMAPLIST <: SCIPType end
type _SCIP_RESOURCEACTIVITY <: SCIPType end
type _SCIP_DIGRAPH <: SCIPType end
type _SCIP_BT <: SCIPType end
type _SCIP_BTNODE <: SCIPType end
type _SCIP_DISPDATA <: SCIPType end
type _SCIP_HISTORY <: SCIPType end
type _SCIP_VALUEHISTORY <: SCIPType end
type _SCIP_NODESELDATA <: SCIPType end
type _SCIP_BASESTAT <: SCIPType end
type _SCIP_EXPR <: SCIPType end
type _SCIP_EXPRDATA_MONOMIAL <: SCIPType end
type _SCIP_EXPRINTDATA <: SCIPType end
type _SCIP_SEPADATA <: SCIPType end
type _SCIP_QUADVARTERM <: SCIPType end
type _SCIP_BILINTERM <: SCIPType end
type _SCIP_MESSAGEHDLRDATA <: SCIPType end
type _SCIP_PARAMDATA <: SCIPType end
type _SCIP_DOMCHG <: SCIPType end
type _SCIP_DIALOGHDLR <: SCIPType end
type _SCIP_DIALOGDATA <: SCIPType end
type _SCIP_VARDATA <: SCIPType end
type _SCIP_HOLELIST <: SCIPType end
type _SCIP_BDCHGINFO <: SCIPType end
type _SCIP_BOUNDCHG <: SCIPType end
type _SCIP_RELAXDATA <: SCIPType end
