# SCIP defines for character, string, and numeric constants
export ARTIFICIALVARNAMEPREFIX, TRUE, FALSE, _SCIP_VERSION, _SCIP_SUBVERSION, _SCIP_COPYRIGHT, _SCIP_VARTYPE_BINARY_CHAR, _SCIP_VARTYPE_INTEGER_CHAR, _SCIP_VARTYPE_IMPLINT_CHAR, _SCIP_VARTYPE_CONTINUOUS_CHAR, _SCIP_LONGINT_FORMAT, _SCIP_REAL_FORMAT, _SCIP_DEFAULT_INFINITY, _SCIP_DEFAULT_EPSILON, _SCIP_DEFAULT_SUMEPSILON, _SCIP_DEFAULT_FEASTOL, _SCIP_DEFAULT_CHECKFEASTOLFAC, _SCIP_DEFAULT_LPFEASTOL, _SCIP_DEFAULT_DUALFEASTOL, _SCIP_DEFAULT_BARRIERCONVTOL, _SCIP_DEFAULT_BOUNDSTREPS, _SCIP_DEFAULT_PSEUDOCOSTEPS, _SCIP_DEFAULT_PSEUDOCOSTDELTA, _SCIP_DEFAULT_RECOMPFAC, _SCIP_DEFAULT_HUGEVAL, _SCIP_MAXEPSILON, _SCIP_MINEPSILON, _SCIP_INVALID, _SCIP_UNKNOWN, _SCIP_MAXSTRLEN, _SCIP_HASHSIZE_PARAMS, _SCIP_HASHSIZE_NAMES, _SCIP_HASHSIZE_CUTPOOLS, _SCIP_HASHSIZE_CLIQUES, _SCIP_HASHSIZE_NAMES_SMALL, _SCIP_HASHSIZE_CUTPOOLS_SMALL, _SCIP_HASHSIZE_CLIQUES_SMALL, _SCIP_HASHSIZE_VBC, _SCIP_DEFAULT_MEM_ARRAYGROWFAC, _SCIP_DEFAULT_MEM_ARRAYGROWINIT, _SCIP_EXPR_DEGREEINFINITY
const ARTIFICIALVARNAMEPREFIX = "andresultant_"
const TRUE = 1
const FALSE = 0
const _SCIP_VERSION = 320
const _SCIP_SUBVERSION = 0
const _SCIP_COPYRIGHT = "Copyright (c) 2002-2015 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)"
const _SCIP_VARTYPE_BINARY_CHAR = 'B'
const _SCIP_VARTYPE_INTEGER_CHAR = 'I'
const _SCIP_VARTYPE_IMPLINT_CHAR = 'M'
const _SCIP_VARTYPE_CONTINUOUS_CHAR = 'C'
const _SCIP_LONGINT_FORMAT = "lld"
const _SCIP_REAL_FORMAT = "lf"
const _SCIP_DEFAULT_INFINITY = 1e+20
const _SCIP_DEFAULT_EPSILON = 1e-09
const _SCIP_DEFAULT_SUMEPSILON = 1e-06
const _SCIP_DEFAULT_FEASTOL = 1e-06
const _SCIP_DEFAULT_CHECKFEASTOLFAC = 1.0
const _SCIP_DEFAULT_LPFEASTOL = 1e-06
const _SCIP_DEFAULT_DUALFEASTOL = 1e-07
const _SCIP_DEFAULT_BARRIERCONVTOL = 1e-10
const _SCIP_DEFAULT_BOUNDSTREPS = 0.05
const _SCIP_DEFAULT_PSEUDOCOSTEPS = 1e-01
const _SCIP_DEFAULT_PSEUDOCOSTDELTA = 1e-04
const _SCIP_DEFAULT_RECOMPFAC = 1e+07
const _SCIP_DEFAULT_HUGEVAL = 1e+15
const _SCIP_MAXEPSILON = 1e-03
const _SCIP_MINEPSILON = 1e-20
const _SCIP_INVALID = 1e+99
const _SCIP_UNKNOWN = 1e+98
const _SCIP_MAXSTRLEN = 1024
const _SCIP_HASHSIZE_PARAMS = 4099
const _SCIP_HASHSIZE_NAMES = 131101
const _SCIP_HASHSIZE_CUTPOOLS = 131101
const _SCIP_HASHSIZE_CLIQUES = 131101
const _SCIP_HASHSIZE_NAMES_SMALL = 8011
const _SCIP_HASHSIZE_CUTPOOLS_SMALL = 8011
const _SCIP_HASHSIZE_CLIQUES_SMALL = 8011
const _SCIP_HASHSIZE_VBC = 131101
const _SCIP_DEFAULT_MEM_ARRAYGROWFAC = 1.2
const _SCIP_DEFAULT_MEM_ARRAYGROWINIT = 4
const _SCIP_EXPR_DEGREEINFINITY = 65535

export _SCIP_DOMCHG, _SCIPbranchruleCompName, _SCIP_HEURDATA, _SCIPvarComp, _SCIP_HEUR, _SCIP_FILE, _SCIPhashKeyValPtr, _SCIPconshdlrCompCheck, _SCIP_PROPDATA, _SCIP_READERDATA, _SCIP_REOPTNODE, _SCIP_REOPT, _SCIP_BOOLARRAY, _SCIP_SOL, _SCIP_BDCHGIDX, _SCIP_MESSAGEHDLR, _SCIPhashGetKeyStandard, _SCIP_COL, _SCIP_PRESOLDATA, _SCIP_PROP, _SCIP_EVENTDATA, _SCIP_EXPRGRAPHNODE, _SCIP_NLPIPROBLEM, _SCIP_COMPR, _SCIP_DISP, _SCIP_EXPRGRAPH, _SCIP_NODESEL, _SCIP_RELAXDATA, _SCIPsepaCompName, _SCIP_EXPRTREE, _SCIP_PRESOL, _SCIPconflicthdlrCompName, _SCIPpropCompName, _SCIP_HOLELIST, _SCIP_BOUNDCHG, _SCIP_ROW, _SCIP_BRANCHRULEDATA, _SCIPcomprComp, _SCIPcomprCompName, _SCIP_PTRARRAY, _SCIPconshdlrCompSepa, _SCIP_HASHMAPLIST, _SCIPvarGetHashkeyVal, _SCIP_VARDATA, _SCIP_NLPI, _SCIP_DIVETYPE, _SCIP_PRICER, _SCIPvarCompObj, _SCIP_DIALOGDATA, _SCIP_EVENTHDLR, _SCIP_HISTORY, _SCIPpricerComp, _SCIP_DIALOGHDLR, _SCIP_DIVESET, _SCIP_VALUEHISTORY, _SCIP_PRICERDATA, _SCIP_CONSHDLRDATA, _SCIP_PROFILE, _SCIP_SEPA, _SCIP_DIGRAPH, _SCIP_CONFLICTHDLR, _SCIPpresolComp, _SCIP_READER, _SCIPrelaxCompName, _SCIP_SPARSESOL, _SCIP_EVENTTYPE, _SCIPheurCompName, _SCIP_PARAMDATA, _SCIP_REALARRAY, _SCIP_HASHMAP, _SCIP_HEURTIMING, _SCIP_BT, _SCIPsepaComp, _SCIP_BRANCHRULE, _SCIPconflicthdlrComp, _SCIP_CONSDATA, _SCIPheurComp, _SCIP_DIALOG, _SCIPpricerCompName, _SCIP_NLROW, _SCIPbranchruleComp, _SCIP_CONFLICTHDLRDATA, _SCIPdialogExecWriteAllsolutions, _SCIP_USEREXPRDATA, _SCIP_EXPRINTCAPABILITY, _SCIP_CLIQUE, _SCIP_NLPSTATISTICS, _SCIP_EXPRDATA_MONOMIAL, _SCIP_NODE, _SCIP_RESOURCEACTIVITY, _SCIP_NODESELDATA, _SCIP_CONSHDLR, _SCIP_COMPRDATA, _SCIP_RELAX, _SCIPnodeCompLowerbound, _SCIP_BDCHGINFO, _SCIP_PROBDATA, _SCIPhashKeyEqPtr, _SCIPsortCompInt, _SCIPrelaxComp, _SCIPvarIsHashkeyEq, _SCIP_QUADVARTERM, _SCIPdialogExecChangeMinUC, _SCIP_SEPADATA, _SCIPvarGetHashkey, _SCIPpropComp, _SCIP_PRESOLTIMING, _SCIPMILPMATRIX, _SCIPhashKeyEqString, _SCIP_PARAM, _SCIP_CUT, _SCIP_EXPRINTDATA, _SCIProwComp, _SCIP_BTNODE, _SCIPconshdlrCompEnfo, _SCIPpropCompPresol, _SCIP_BILINTERM, _SCIP_MESSAGEHDLRDATA, _SCIPdialogExecCount, _SCIP_PROPTIMING, _SCIP_DISPDATA, _SCIP_EVENTHDLRDATA, _SCIP_QUEUE, _SCIP_CONS, _SCIP_CUTPOOL, _SCIP_INTERVAL, _SCIP_HASHTABLELIST, _SCIP_LPI, _SCIPhashKeyValString, _SCIPpresolCompName, _SCIP_INTARRAY, _SCIP_VAR, _SCIP_EVENT, _SCIP_PQUEUE, _SCIP_HASHTABLE, _SCIPvarCompActiveAndNegated, _SCIP_CLOCK, _SCIP, _SCIPdialogExecCountPresolve, _SCIP_EXPR, _SCIP_QUADELEM
abstract SCIPType
export SCIPType
type _SCIP <: SCIPType end
type _SCIPMILPMATRIX <: SCIPType end
type _SCIP_BDCHGIDX <: SCIPType end
type _SCIP_BDCHGINFO <: SCIPType end
type _SCIP_BILINTERM <: SCIPType end
type _SCIP_BOOLARRAY <: SCIPType end
type _SCIP_BOUNDCHG <: SCIPType end
type _SCIP_BRANCHRULE <: SCIPType end
type _SCIP_BRANCHRULEDATA <: SCIPType end
type _SCIP_BT <: SCIPType end
type _SCIP_BTNODE <: SCIPType end
type _SCIP_CLIQUE <: SCIPType end
type _SCIP_CLOCK <: SCIPType end
type _SCIP_COL <: SCIPType end
type _SCIP_COMPR <: SCIPType end
type _SCIP_COMPRDATA <: SCIPType end
type _SCIP_CONFLICTHDLR <: SCIPType end
type _SCIP_CONFLICTHDLRDATA <: SCIPType end
type _SCIP_CONS <: SCIPType end
type _SCIP_CONSDATA <: SCIPType end
type _SCIP_CONSHDLR <: SCIPType end
type _SCIP_CONSHDLRDATA <: SCIPType end
type _SCIP_CUT <: SCIPType end
type _SCIP_CUTPOOL <: SCIPType end
type _SCIP_DIALOG <: SCIPType end
type _SCIP_DIALOGDATA <: SCIPType end
type _SCIP_DIALOGHDLR <: SCIPType end
type _SCIP_DIGRAPH <: SCIPType end
type _SCIP_DISP <: SCIPType end
type _SCIP_DISPDATA <: SCIPType end
type _SCIP_DIVESET <: SCIPType end
type _SCIP_DIVETYPE <: SCIPType end
type _SCIP_DOMCHG <: SCIPType end
type _SCIP_EVENT <: SCIPType end
type _SCIP_EVENTDATA <: SCIPType end
type _SCIP_EVENTHDLR <: SCIPType end
type _SCIP_EVENTHDLRDATA <: SCIPType end
type _SCIP_EVENTTYPE <: SCIPType end
type _SCIP_EXPR <: SCIPType end
type _SCIP_EXPRDATA_MONOMIAL <: SCIPType end
type _SCIP_EXPRGRAPH <: SCIPType end
type _SCIP_EXPRGRAPHNODE <: SCIPType end
type _SCIP_EXPRINTCAPABILITY <: SCIPType end
type _SCIP_EXPRINTDATA <: SCIPType end
type _SCIP_EXPRTREE <: SCIPType end
type _SCIP_FILE <: SCIPType end
type _SCIP_HASHMAP <: SCIPType end
type _SCIP_HASHMAPLIST <: SCIPType end
type _SCIP_HASHTABLE <: SCIPType end
type _SCIP_HASHTABLELIST <: SCIPType end
type _SCIP_HEUR <: SCIPType end
type _SCIP_HEURDATA <: SCIPType end
type _SCIP_HEURTIMING <: SCIPType end
type _SCIP_HISTORY <: SCIPType end
type _SCIP_HOLELIST <: SCIPType end
type _SCIP_INTARRAY <: SCIPType end
type _SCIP_INTERVAL <: SCIPType end
type _SCIP_LPI <: SCIPType end
type _SCIP_MESSAGEHDLR <: SCIPType end
type _SCIP_MESSAGEHDLRDATA <: SCIPType end
type _SCIP_NLPI <: SCIPType end
type _SCIP_NLPIPROBLEM <: SCIPType end
type _SCIP_NLPSTATISTICS <: SCIPType end
type _SCIP_NLROW <: SCIPType end
type _SCIP_NODE <: SCIPType end
type _SCIP_NODESEL <: SCIPType end
type _SCIP_NODESELDATA <: SCIPType end
type _SCIP_PARAM <: SCIPType end
type _SCIP_PARAMDATA <: SCIPType end
type _SCIP_PQUEUE <: SCIPType end
type _SCIP_PRESOL <: SCIPType end
type _SCIP_PRESOLDATA <: SCIPType end
type _SCIP_PRESOLTIMING <: SCIPType end
type _SCIP_PRICER <: SCIPType end
type _SCIP_PRICERDATA <: SCIPType end
type _SCIP_PROBDATA <: SCIPType end
type _SCIP_PROFILE <: SCIPType end
type _SCIP_PROP <: SCIPType end
type _SCIP_PROPDATA <: SCIPType end
type _SCIP_PROPTIMING <: SCIPType end
type _SCIP_PTRARRAY <: SCIPType end
type _SCIP_QUADELEM <: SCIPType end
type _SCIP_QUADVARTERM <: SCIPType end
type _SCIP_QUEUE <: SCIPType end
type _SCIP_READER <: SCIPType end
type _SCIP_READERDATA <: SCIPType end
type _SCIP_REALARRAY <: SCIPType end
type _SCIP_RELAX <: SCIPType end
type _SCIP_RELAXDATA <: SCIPType end
type _SCIP_REOPT <: SCIPType end
type _SCIP_REOPTNODE <: SCIPType end
type _SCIP_RESOURCEACTIVITY <: SCIPType end
type _SCIP_ROW <: SCIPType end
type _SCIP_SEPA <: SCIPType end
type _SCIP_SEPADATA <: SCIPType end
type _SCIP_SOL <: SCIPType end
type _SCIP_SPARSESOL <: SCIPType end
type _SCIP_USEREXPRDATA <: SCIPType end
type _SCIP_VALUEHISTORY <: SCIPType end
type _SCIP_VAR <: SCIPType end
type _SCIP_VARDATA <: SCIPType end
type _SCIPbranchruleComp <: SCIPType end
type _SCIPbranchruleCompName <: SCIPType end
type _SCIPcomprComp <: SCIPType end
type _SCIPcomprCompName <: SCIPType end
type _SCIPconflicthdlrComp <: SCIPType end
type _SCIPconflicthdlrCompName <: SCIPType end
type _SCIPconshdlrCompCheck <: SCIPType end
type _SCIPconshdlrCompEnfo <: SCIPType end
type _SCIPconshdlrCompSepa <: SCIPType end
type _SCIPdialogExecChangeMinUC <: SCIPType end
type _SCIPdialogExecCount <: SCIPType end
type _SCIPdialogExecCountPresolve <: SCIPType end
type _SCIPdialogExecWriteAllsolutions <: SCIPType end
type _SCIPhashGetKeyStandard <: SCIPType end
type _SCIPhashKeyEqPtr <: SCIPType end
type _SCIPhashKeyEqString <: SCIPType end
type _SCIPhashKeyValPtr <: SCIPType end
type _SCIPhashKeyValString <: SCIPType end
type _SCIPheurComp <: SCIPType end
type _SCIPheurCompName <: SCIPType end
type _SCIPnodeCompLowerbound <: SCIPType end
type _SCIPpresolComp <: SCIPType end
type _SCIPpresolCompName <: SCIPType end
type _SCIPpricerComp <: SCIPType end
type _SCIPpricerCompName <: SCIPType end
type _SCIPpropComp <: SCIPType end
type _SCIPpropCompName <: SCIPType end
type _SCIPpropCompPresol <: SCIPType end
type _SCIPrelaxComp <: SCIPType end
type _SCIPrelaxCompName <: SCIPType end
type _SCIProwComp <: SCIPType end
type _SCIPsepaComp <: SCIPType end
type _SCIPsepaCompName <: SCIPType end
type _SCIPsortCompInt <: SCIPType end
type _SCIPvarComp <: SCIPType end
type _SCIPvarCompActiveAndNegated <: SCIPType end
type _SCIPvarCompObj <: SCIPType end
type _SCIPvarGetHashkey <: SCIPType end
type _SCIPvarGetHashkeyVal <: SCIPType end
type _SCIPvarIsHashkeyEq <: SCIPType end

