# SCIP defines for character, string, and numeric constants
export ARTIFICIALVARNAMEPREFIX, TRUE, FALSE, _SCIP_VERSION, _SCIP_SUBVERSION, _SCIP_COPYRIGHT, _SCIP_VARTYPE_BINARY_CHAR, _SCIP_VARTYPE_INTEGER_CHAR, _SCIP_VARTYPE_IMPLINT_CHAR, _SCIP_VARTYPE_CONTINUOUS_CHAR, _SCIP_LONGINT_FORMAT, _SCIP_REAL_FORMAT, _SCIP_MAXSTRLEN, _SCIP_HASHSIZE_PARAMS, _SCIP_HASHSIZE_NAMES, _SCIP_HASHSIZE_CUTPOOLS, _SCIP_HASHSIZE_CLIQUES, _SCIP_HASHSIZE_NAMES_SMALL, _SCIP_HASHSIZE_CUTPOOLS_SMALL, _SCIP_HASHSIZE_CLIQUES_SMALL, _SCIP_HASHSIZE_VBC, _SCIP_EXPR_DEGREEINFINITY
const ARTIFICIALVARNAMEPREFIX = "andresultant_"
const TRUE = 1
const FALSE = 0
const _SCIP_VERSION = 310
const _SCIP_SUBVERSION = 0
const _SCIP_COPYRIGHT = "Copyright (c) 2002-2014 Konrad-Zuse-Zentrum fuer Informationstechnik Berlin (ZIB)"
const _SCIP_VARTYPE_BINARY_CHAR = 'B'
const _SCIP_VARTYPE_INTEGER_CHAR = 'I'
const _SCIP_VARTYPE_IMPLINT_CHAR = 'M'
const _SCIP_VARTYPE_CONTINUOUS_CHAR = 'C'
const _SCIP_LONGINT_FORMAT = "lld"
const _SCIP_REAL_FORMAT = "lf"
const _SCIP_MAXSTRLEN = 1024
const _SCIP_HASHSIZE_PARAMS = 4099
const _SCIP_HASHSIZE_NAMES = 131101
const _SCIP_HASHSIZE_CUTPOOLS = 131101
const _SCIP_HASHSIZE_CLIQUES = 131101
const _SCIP_HASHSIZE_NAMES_SMALL = 8011
const _SCIP_HASHSIZE_CUTPOOLS_SMALL = 8011
const _SCIP_HASHSIZE_CLIQUES_SMALL = 8011
const _SCIP_HASHSIZE_VBC = 131101
const _SCIP_EXPR_DEGREEINFINITY = 65535

# SCIP defines for known C types and pointers to SCIP structs.
export _SCIP, _SCIP_CONS, _SCIP_VAR, _SCIP_Real, _SCIP_Bool, _SCIP_NLROW, _SCIP_SOL, _SCIP_EXPRTREE, _SCIP_PROFILE, _SCIP_CONSHDLR, _SCIP_ROW, _SCIP_SEPA, _SCIP_HASHMAP, _SCIP_EXPRGRAPHNODE, _SCIP_EXPRGRAPH, _SCIP_QUADVARTERM, _SCIP_BILINTERM, _SCIP_NLPI, _SCIP_NLPIPROBLEM, _SCIP_BRANCHRULEDATA, _SCIP_BRANCHRULE, _SCIP_CONFLICTHDLRDATA, _SCIP_CONFLICTHDLR, _SCIP_CONSHDLRDATA, _SCIP_PROPTIMING, _SCIP_CONSDATA, _SCIP_CUT, _SCIP_CUTPOOL, _SCIP_DIALOG, _SCIP_DIALOGHDLR, _SCIP_DIALOGDATA, _SCIP_DISPDATA, _SCIP_DISP, _SCIP_MESSAGEHDLR, _SCIP_EVENTHDLR, _SCIP_EVENTHDLRDATA, _SCIP_EVENTTYPE, _SCIP_EVENT, _SCIP_NODE, _SCIP_COL, _SCIP_INTERVAL, _SCIP_EXPR, _SCIP_QUADELEM, _SCIP_EXPRDATA_MONOMIAL, _SCIP_EXPRINTDATA, _SCIP_HEURDATA, _SCIP_HEUR, _SCIP_HEURTIMING, _SCIP_HISTORY, _SCIP_VALUEHISTORY, _SCIP_CLIQUE, _SCIP_BASESTAT, _SCIP_MESSAGEHDLRDATA, _SCIP_SPARSESOL, _SCIP_QUEUE, _SCIP_PQUEUE, _SCIP_HASHTABLE, _SCIP_HASHMAPLIST, _SCIP_RESOURCEACTIVITY, _SCIP_DIGRAPH, _SCIP_BT, _SCIP_BTNODE, _SCIP_NODESEL, _SCIP_NODESELDATA, _SCIP_PARAM, _SCIP_PARAMDATA, _SCIP_PRESOLDATA, _SCIP_PRESOL, _SCIP_PRICERDATA, _SCIP_PRICER, _SCIP_PROPDATA, _SCIP_PROP, _SCIP_READERDATA, _SCIP_READER, _SCIP_RELAXDATA, _SCIP_RELAX, _SCIP_SEPADATA, _SCIP_DOMCHG, _SCIP_VARDATA, _SCIP_HOLELIST, _SCIP_BDCHGINFO, _SCIP_BDCHGIDX, _SCIP_BOUNDCHG, _SCIP_PROBDATA, _SCIP_REALARRAY, _SCIP_LPI, _SCIP_NLPSTATISTICS, _SCIP_EVENTDATA, _SCIP_CLOCK, _SCIP_INTARRAY, _SCIP_BOOLARRAY, _SCIP_PTRARRAY
abstract SCIPType
export SCIPType
# typealias _SCIP Void
type _SCIP <: SCIPType end
# typealias _SCIP_CONS Void
type _SCIP_CONS <: SCIPType end
# typealias _SCIP_VAR Void
type _SCIP_VAR <: SCIPType end
typealias _SCIP_Real Float64
typealias _SCIP_Bool Uint
typealias _SCIP_NLROW Void
typealias _SCIP_SOL Void
typealias _SCIP_EXPRTREE Void
typealias _SCIP_PROFILE Void
typealias _SCIP_CONSHDLR Void
typealias _SCIP_ROW Void
typealias _SCIP_SEPA Void
typealias _SCIP_HASHMAP Void
typealias _SCIP_EXPRGRAPHNODE Void
typealias _SCIP_EXPRGRAPH Void
typealias _SCIP_QUADVARTERM Void
typealias _SCIP_BILINTERM Void
typealias _SCIP_NLPI Void
typealias _SCIP_NLPIPROBLEM Void
typealias _SCIP_BRANCHRULEDATA Void
typealias _SCIP_BRANCHRULE Void
typealias _SCIP_CONFLICTHDLRDATA Void
typealias _SCIP_CONFLICTHDLR Void
typealias _SCIP_CONSHDLRDATA Void
typealias _SCIP_PROPTIMING Void
typealias _SCIP_CONSDATA Void
typealias _SCIP_CUT Void
typealias _SCIP_CUTPOOL Void
typealias _SCIP_DIALOG Void
typealias _SCIP_DIALOGHDLR Void
typealias _SCIP_DIALOGDATA Void
typealias _SCIP_DISPDATA Void
typealias _SCIP_DISP Void
typealias _SCIP_MESSAGEHDLR Void
typealias _SCIP_EVENTHDLR Void
typealias _SCIP_EVENTHDLRDATA Void
typealias _SCIP_EVENTTYPE Void
typealias _SCIP_EVENT Void
typealias _SCIP_NODE Void
typealias _SCIP_COL Void
typealias _SCIP_INTERVAL Void
typealias _SCIP_EXPR Void
typealias _SCIP_QUADELEM Void
typealias _SCIP_EXPRDATA_MONOMIAL Void
typealias _SCIP_EXPRINTDATA Void
typealias _SCIP_HEURDATA Void
typealias _SCIP_HEUR Void
typealias _SCIP_HEURTIMING Void
typealias _SCIP_HISTORY Void
typealias _SCIP_VALUEHISTORY Void
typealias _SCIP_CLIQUE Void
typealias _SCIP_BASESTAT Void
typealias _SCIP_MESSAGEHDLRDATA Void
typealias _SCIP_SPARSESOL Void
typealias _SCIP_QUEUE Void
typealias _SCIP_PQUEUE Void
typealias _SCIP_HASHTABLE Void
typealias _SCIP_HASHMAPLIST Void
typealias _SCIP_RESOURCEACTIVITY Void
typealias _SCIP_DIGRAPH Void
typealias _SCIP_BT Void
typealias _SCIP_BTNODE Void
typealias _SCIP_NODESEL Void
typealias _SCIP_NODESELDATA Void
typealias _SCIP_PARAM Void
typealias _SCIP_PARAMDATA Void
typealias _SCIP_PRESOLDATA Void
typealias _SCIP_PRESOL Void
typealias _SCIP_PRICERDATA Void
typealias _SCIP_PRICER Void
typealias _SCIP_PROPDATA Void
typealias _SCIP_PROP Void
typealias _SCIP_READERDATA Void
typealias _SCIP_READER Void
typealias _SCIP_RELAXDATA Void
typealias _SCIP_RELAX Void
typealias _SCIP_SEPADATA Void
typealias _SCIP_DOMCHG Void
typealias _SCIP_VARDATA Void
typealias _SCIP_HOLELIST Void
typealias _SCIP_BDCHGINFO Void
typealias _SCIP_BDCHGIDX Void
typealias _SCIP_BOUNDCHG Void
typealias _SCIP_PROBDATA Void
typealias _SCIP_REALARRAY Void
typealias _SCIP_LPI Void
typealias _SCIP_NLPSTATISTICS Void
typealias _SCIP_EVENTDATA Void
typealias _SCIP_CLOCK Void
typealias _SCIP_INTARRAY Void
typealias _SCIP_BOOLARRAY Void
typealias _SCIP_PTRARRAY Void
