typealias SCIP_Objsense Int8

SCIP_OBJSENSE_MAXIMIZE = int8(-1)
SCIP_OBJSENSE_MINIMIZE = int8(+1)

SCIP_OBJSENSE = Dict{SCIP_Objsense, String}()
SCIP_OBJSENSE[SCIP_OBJSENSE_MAXIMIZE] = "maximize"
SCIP_OBJSENSE[SCIP_OBJSENSE_MINIMIZE] = "minimize"