exprinterpret_cppad.cpp
SIGN
sign of a value (-1 or +1)0.0 has sign +1
SCIPInterval_NAMESPACE
CPPAD_MAX_NUM_THREADS
pthread_mutex_t cppadmutex
mutex for locking in pthread case
pthread_key_t thread_specific_key
key for accessing thread specific information
size_t ncurthreads
currently registered number of threads
char init_parallel_return
a dummy variable that can is initialized to the result of init_parallelThe purpose is to make sure that init_parallel() is called before any multithreading is started.
static bool in_parallel(void)
CppAD callback function that indicates whether we are running in parallel mode
static size_t thread_num(void)
CppAD callback function that returns the number of the current threadassigns a new number to the thread if new
static char init_parallel(void)
sets up CppAD's datastructures for running in multithreading modeIt must be called once before multithreading is started.
SCIPInterval CondExpOp(enum CppAD::CompareOp cop, const SCIPInterval &left, const SCIPInterval &right, const SCIPInterval &trueCase, const SCIPInterval &falseCase)
definition of CondExpOp for SCIPInterval (required by CppAD)
bool EqualOpSeq(const SCIPInterval &x, const SCIPInterval &y)
first operand
another function that returns whether two intervals are the same (required by CppAD)
bool IdenticalPar(const SCIPInterval &x)
operand
another function required by CppAD
bool IdenticalZero(const SCIPInterval &x)
operand
returns whether the interval equals [0,0]
bool IdenticalOne(const SCIPInterval &x)
operand
returns whether the interval equals [1,1]
bool IdenticalEqualPar(const SCIPInterval &x, const SCIPInterval &y)
first operand
yet another function that checks whether two intervals are equal
bool GreaterThanZero(const SCIPInterval &x)
operand
greater than zero not defined for intervals
bool GreaterThanOrZero(const SCIPInterval &x)
operand
greater than or equal zero not defined for intervals
bool LessThanZero(const SCIPInterval &x)
operand
less than not defined for intervals
bool LessThanOrZero(const SCIPInterval &x)
operand
less than or equal not defined for intervals
int Integer(const SCIPInterval &x)
operand
conversion to integers not defined for intervals
std::ostream& operator<<(std::ostream &out, const SCIP_INTERVAL &x)
printing of an interval (required by CppAD)
static bool univariate_for_sparse_jac(size_t q, const CppAD::vector< bool > &r, CppAD::vector< bool > &s)
number of columns in R
computes sparsity of jacobian for a univariate function during a forward sweepFor a 1 x q matrix R, we have to return the sparsity pattern of the 1 x q matrix S(x) = f'(x) * R. Since f'(x) is dense, the sparsity of S will be the sparsity of R.
static bool univariate_rev_sparse_jac(size_t q, const CppAD::vector< bool > &r, CppAD::vector< bool > &s)
number of rows in R
Computes sparsity of jacobian during a reverse sweepFor a q x 1 matrix R, we have to return the sparsity pattern of the q x 1 matrix S(x) = R * f'(x). Since f'(x) is dense, the sparsity of S will be the sparsity of R.
static bool univariate_rev_sparse_hes(const CppAD::vector< bool > &vx, const CppAD::vector< bool > &s, CppAD::vector< bool > &t, size_t q, const CppAD::vector< bool > &r, const CppAD::vector< bool > &u, CppAD::vector< bool > &v)
indicates whether argument is a variable, or empty vector
computes sparsity of hessian during a reverse sweepAssume V(x) = (g(f(x)))'' R with f(x) = x^p for a function g:R->R and a matrix R. we have to specify the sparsity pattern of V(x) and T(x) = (g(f(x)))'.
static void posintpower(const vector< Type > &in, vector< Type > &out, size_t exponent)
vector which first argument is base
power function with natural exponents
static void evalSignPower(Type &resultant, const Type &arg, SCIP_EXPR *expr)
resultant
template for evaluation for signpower operator
SCIP_RETCODE exprEvalUser(SCIP_EXPR *expr, Type *x, Type &funcval, Type *gradient, Type *hessian)
References SCIPexprEvalUser.
SCIP_RETCODE exprEvalUser(SCIP_EXPR *expr, SCIPInterval *x, SCIPInterval &funcval, SCIPInterval *gradient, SCIPInterval *hessian)
References SCIPexprEvalIntUser.
static void evalUser(Type &resultant, const Type *args, SCIP_EXPR *expr)
resultant
static void evalMin(Type &resultant, const Type &arg1, const Type &arg2)
resultant
template for evaluation for minimum operatorOnly implemented for real numbers, thus gives error by default.
void evalMin(CppAD::AD< double > &resultant, const CppAD::AD< double > &arg1, const CppAD::AD< double > &arg2)
resultant
specialization of minimum evaluation for real numbers
References MIN.
static void evalMax(Type &resultant, const Type &arg1, const Type &arg2)
resultant
template for evaluation for maximum operatorOnly implemented for real numbers, thus gives error by default.
void evalMax(CppAD::AD< double > &resultant, const CppAD::AD< double > &arg1, const CppAD::AD< double > &arg2)
resultant
specialization of maximum evaluation for real numbers
References MAX.
static void evalSqrt(Type &resultant, const Type &arg)
resultant
template for evaluation for square-root operatorDefault is to use the standard sqrt-function.
static void evalAbs(Type &resultant, const Type &arg)
resultant
template for evaluation for absolute value operator
void evalAbs(CppAD::AD< SCIPInterval > &resultant, const CppAD::AD< SCIPInterval > &arg)
resultant
specialization of absolute value evaluation for intervalsUse sqrt(x^2) for now
static void evalIntPower(Type &resultant, const Type &arg, const int exponent)
resultant
integer power operation for arbitrary integer exponents
static SCIP_RETCODE eval(SCIP_EXPR *expr, const vector< Type > &x, SCIP_Real *param, Type &val)
expression
CppAD compatible evaluation of an expression for given arguments and parameters
static void analyzeTree(SCIP_EXPRINTDATA *data, SCIP_EXPR *expr)
analysis an expression tree whether it requires retaping on every evaluationThis may be the case if the evaluation sequence depends on values of operands (e.g., in case of abs, sign, signpower, ...).
static void cppaderrorcallback(bool known, int line, const char *file, const char *cond, const char *msg)
is the error from a known source?
replacement for CppAD's default error handlerIn debug mode, CppAD gives an error when an evaluation contains a nan. We do not want to stop execution in such a case, since the calling routine should check for nan's and decide what to do. Since we cannot ignore this particular error, we ignore all.
static CppAD::ErrorHandler errorhandler(cppaderrorcallback)
const char* SCIPexprintGetName(void)
gets name and version of expression interpreter
const char* SCIPexprintGetDesc(void)
gets descriptive text of expression interpreter
SCIP_EXPRINTCAPABILITY SCIPexprintGetCapability(void)
gets capabilities of expression interpreter (using bitflags)
References SCIP_EXPRINTCAPABILITY_FUNCVALUE, SCIP_EXPRINTCAPABILITY_GRADIENT, SCIP_EXPRINTCAPABILITY_HESSIAN, SCIP_EXPRINTCAPABILITY_INTFUNCVALUE, SCIP_EXPRINTCAPABILITY_INTGRADIENT.
SCIP_RETCODE SCIPexprintCreate(BMS_BLKMEM *blkmem, SCIP_EXPRINT **exprint)
block memory data structure
creates an expression interpreter object
References NULL, SCIP_NOMEMORY, SCIP_OKAY.
SCIP_RETCODE SCIPexprintFree(SCIP_EXPRINT **exprint)
expression interpreter that should be freed
frees an expression interpreter object
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPexprintCompile(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree)
interpreter data structure
compiles an expression tree and stores compiled data in expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SCIPexprCopyDeep, SCIPexprFreeDeep, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetRoot, SCIPexprtreeSetInterpreterData.
SCIP_EXPRINTCAPABILITY SCIPexprintGetExprtreeCapability(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree)
interpreter data structure
gives the capability to evaluate an expression by the expression interpreterIn cases of user-given expressions, higher order derivatives may not be available for the user-expression, even if the expression interpreter could handle these. This method allows to recognize that, e.g., the Hessian for an expression is not available because it contains a user expression that does not provide Hessians.
References NULL, SCIPexprtreeGetInterpreterData.
SCIP_RETCODE SCIPexprintFreeData(SCIP_EXPRINTDATA **interpreterdata)
interpreter data that should freed
frees interpreter data
References NULL, SCIP_OKAY, SCIPexprFreeDeep.
SCIP_RETCODE SCIPexprintNewParametrization(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree)
interpreter data structure
notify expression interpreter that a new parameterization is usedThis probably causes retaping by AD algorithms.
References NULL, SCIP_OKAY, SCIPexprtreeGetInterpreterData.
SCIP_RETCODE SCIPexprintEval(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Real *val)
interpreter data structure
evaluates an expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SCIPexprtreeEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetParamVals, SCIPexprtreeGetRoot.
Referenced by SCIPexprintGrad, SCIPexprintHessianDense, SCIPexprintHessianSparsityDense.
SCIP_RETCODE SCIPexprintEvalInt(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_INTERVAL *val)
interpreter data structure
evaluates an expression tree on intervals
References NULL, SCIP_CALL, SCIP_OKAY, SCIPexprtreeEvalInt, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetParamVals, SCIPexprtreeGetRoot.
Referenced by SCIPexprintGradInt.
SCIP_RETCODE SCIPexprintGrad(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool new_varvals, SCIP_Real *val, SCIP_Real *gradient)
interpreter data structure
computes value and gradient of an expression tree
References FALSE, NULL, SCIP_CALL, SCIP_OKAY, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.
SCIP_RETCODE SCIPexprintGradInt(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_Bool new_varvals, SCIP_INTERVAL *val, SCIP_INTERVAL *gradient)
interpreter data structure
computes interval value and interval gradient of an expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIPexprintEvalInt, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.
SCIP_RETCODE SCIPexprintHessianSparsityDense(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool *sparsity)
interpreter data structure
gives sparsity pattern of hessianNOTE: this function might be replaced later by something nicer. Since the AD code might need to do a forward sweep, you should pass variable values in here.
References NULL, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, TRUE.
SCIP_RETCODE SCIPexprintHessianDense(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool new_varvals, SCIP_Real *val, SCIP_Real *hessian)
interpreter data structure
computes value and dense hessian of an expression treeThe full hessian is computed (lower left and upper right triangle).
References FALSE, NULL, SCIP_CALL, SCIP_OKAY, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.