exprinterpret.h
const char* SCIPexprintGetName(void)
gets name and version of expression interpreter
const char* SCIPexprintGetDesc(void)
gets descriptive text of expression interpreter
SCIP_EXPRINTCAPABILITY SCIPexprintGetCapability(void)
gets capabilities of expression interpreter (using bitflags)
References SCIP_EXPRINTCAPABILITY_FUNCVALUE, SCIP_EXPRINTCAPABILITY_GRADIENT, SCIP_EXPRINTCAPABILITY_HESSIAN, SCIP_EXPRINTCAPABILITY_INTFUNCVALUE, SCIP_EXPRINTCAPABILITY_INTGRADIENT, SCIP_EXPRINTCAPABILITY_NONE.
SCIP_RETCODE SCIPexprintCreate(BMS_BLKMEM *blkmem, SCIP_EXPRINT **exprint)
block memory data structure
creates an expression interpreter object
References NULL, SCIP_ALLOC, SCIP_NOMEMORY, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPexprintFree(SCIP_EXPRINT **exprint)
expression interpreter that should be freed
frees an expression interpreter object
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPexprintCompile(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree)
interpreter data structure
compiles an expression tree and stores compiled data in expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SCIPexprCopyDeep, SCIPexprFreeDeep, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetRoot, SCIPexprtreeSetInterpreterData.
SCIP_RETCODE SCIPexprintFreeData(SCIP_EXPRINTDATA **interpreterdata)
interpreter data that should freed
frees interpreter data
References NULL, SCIP_OKAY, SCIPexprFreeDeep.
SCIP_RETCODE SCIPexprintNewParametrization(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree)
interpreter data structure
notify expression interpreter that a new parameterization is used this probably causes retaping by AD algorithms
References NULL, SCIP_OKAY, SCIPexprtreeGetInterpreterData.
SCIP_RETCODE SCIPexprintEval(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Real *val)
interpreter data structure
evaluates an expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetParamVals, SCIPexprtreeGetRoot.
Referenced by SCIPexprintGrad, SCIPexprintHessianDense, SCIPexprintHessianSparsityDense.
SCIP_RETCODE SCIPexprintEvalInt(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_INTERVAL *val)
interpreter data structure
evaluates an expression tree on intervals
References NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPerrorMessage, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, SCIPexprtreeGetParamVals, SCIPexprtreeGetRoot.
Referenced by SCIPexprintGradInt.
SCIP_RETCODE SCIPexprintGrad(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool new_varvals, SCIP_Real *val, SCIP_Real *gradient)
interpreter data structure
computes value and gradient of an expression tree
References FALSE, NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPerrorMessage, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.
SCIP_RETCODE SCIPexprintGradInt(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_Bool new_varvals, SCIP_INTERVAL *val, SCIP_INTERVAL *gradient)
interpreter data structure
computes interval value and interval gradient of an expression tree
References NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPerrorMessage, SCIPexprintEvalInt, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.
SCIP_RETCODE SCIPexprintHessianSparsityDense(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool *sparsity)
interpreter data structure
gives sparsity pattern of hessian NOTE: this function might be replaced later by something nicer Since the AD code might need to do a forward sweep, you should pass variable values in here.
References NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, SCIPerrorMessage, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars, TRUE.
SCIP_RETCODE SCIPexprintHessianDense(SCIP_EXPRINT *exprint, SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Bool new_varvals, SCIP_Real *val, SCIP_Real *hessian)
interpreter data structure
computes value and dense hessian of an expression tree the full hessian is computed (lower left and upper right triangle)
References FALSE, NULL, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPerrorMessage, SCIPexprintEval, SCIPexprtreeGetInterpreterData, SCIPexprtreeGetNVars.