lpi_spx.cpp
const char* SCIPlpiGetSolverName(void)
gets name and version of LP solver
References SCIPdebugMessage, SOPLEX_SUBVERSION.
const char* SCIPlpiGetSolverDesc(void)
gets description of LP solver (developer, webpage, ...)
void* SCIPlpiGetSolverPointer(SCIP_LPI *lpi)
pointer to an LP interface structure
gets pointer for LP solver - use only with great care
SCIP_RETCODE SCIPlpiCreate(SCIP_LPI **lpi, SCIP_MESSAGEHDLR *messagehdlr, const char *name, SCIP_OBJSEN objsen)
pointer to an LP interface structure
creates an LP problem object
References FALSE, NULL, SCIP_ALLOC, SCIP_CALL, SCIP_LPPAR_PRICING, SCIP_OKAY, SCIP_PRICING_LPIDEFAULT, SCIPlpiChgObjsen, SCIPlpiInfinity, SCIPlpiSetIntpar, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiFree(SCIP_LPI **lpi)
pointer to an LP interface structure
deletes an LP problem object
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiLoadColLP(SCIP_LPI *lpi, SCIP_OBJSEN objsen, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **colnames, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
copies LP data with column matrix into LP solver
References NULL, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPlpiAddCols, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiAddCols(SCIP_LPI *lpi, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds columns to the LP
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
Referenced by SCIPlpiLoadColLP.
SCIP_RETCODE SCIPlpiDelCols(SCIP_LPI *lpi, int firstcol, int lastcol)
LP interface structure
deletes all columns in the given range from LP
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiDelColset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes columns from SCIP_LP; the new position of a column must not be greater that its old position
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiAddRows(SCIP_LPI *lpi, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds rows to the LP
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiDelRows(SCIP_LPI *lpi, int firstrow, int lastrow)
LP interface structure
deletes all rows in the given range from LP
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiDelRowset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes rows from SCIP_LP; the new position of a row must not be greater that its old position
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiClear(SCIP_LPI *lpi)
LP interface structure
clears the whole LP
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiChgBounds(SCIP_LPI *lpi, int ncols, const int *ind, const SCIP_Real *lb, const SCIP_Real *ub)
LP interface structure
changes lower and upper bounds of columns
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiChgSides(SCIP_LPI *lpi, int nrows, const int *ind, const SCIP_Real *lhs, const SCIP_Real *rhs)
LP interface structure
changes left and right hand sides of rows
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiChgCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real newval)
LP interface structure
changes a single coefficient
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiChgObjsen(SCIP_LPI *lpi, SCIP_OBJSEN objsen)
LP interface structure
changes the objective sense
References NULL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
Referenced by SCIPlpiCreate.
SCIP_RETCODE SCIPlpiChgObj(SCIP_LPI *lpi, int ncols, int *ind, SCIP_Real *obj)
LP interface structure
changes objective values of columns in the LP
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiScaleRow(SCIP_LPI *lpi, int row, SCIP_Real scaleval)
LP interface structure
multiplies a row with a non-zero scalar; for negative scalars, the row's sense is switched accordingly
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiScaleCol(SCIP_LPI *lpi, int col, SCIP_Real scaleval)
LP interface structure
multiplies a column with a non-zero scalar; the objective value is multiplied with the scalar, and the bounds are divided by the scalar; for negative scalars, the column's bounds are switched
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetNRows(SCIP_LPI *lpi, int *nrows)
LP interface structure
gets the number of rows in the LP
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNCols(SCIP_LPI *lpi, int *ncols)
LP interface structure
gets the number of columns in the LP
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNNonz(SCIP_LPI *lpi, int *nnonz)
LP interface structure
gets the number of nonzero elements in the LP constraint matrix
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetCols(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lb, SCIP_Real *ub, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets columns from LP problem object; the arrays have to be large enough to store all values Either both, lb and ub, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetRows(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhs, SCIP_Real *rhs, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets rows from LP problem object; the arrays have to be large enough to store all values. Either both, lhs and rhs, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetColNames(SCIP_LPI *lpi, int firstcol, int lastcol, char **colnames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets column names
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetRowNames(SCIP_LPI *lpi, int firstrow, int lastrow, char **rownames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets row names
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetObjsen(SCIP_LPI *lpi, SCIP_OBJSEN *objsen)
LP interface structure
gets objective sense of the LP
References NULL, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetObj(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *vals)
LP interface structure
gets objective coefficients from LP problem object
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetBounds(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lbs, SCIP_Real *ubs)
LP interface structure
gets current bounds from LP problem object
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetSides(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhss, SCIP_Real *rhss)
LP interface structure
gets current row sides from LP problem object
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real *val)
LP interface structure
gets a single coefficient
References NULL, SCIP_OKAY, SCIPdebugMessage.
static SCIP_RETCODE spxSolve(SCIP_LPI *lpi, SPxSolver::Representation rep, SPxSolver::Type type)
LP interface structure
solves LP used for both, primal and dual simplex, because SoPlex doesn't distinct the two cases
SCIP_RETCODE SCIPlpiSolvePrimal(SCIP_LPI *lpi)
LP interface structure
calls primal simplex to solve the LP
References FALSE, NULL, SCIP_Bool, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSolveDual(SCIP_LPI *lpi)
LP interface structure
calls dual simplex to solve the LP
References FALSE, NULL, SCIP_Bool, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSolveBarrier(SCIP_LPI *lpi, SCIP_Bool crossover)
LP interface structure
calls barrier or interior point algorithm to solve the LP with crossover to simplex basis
References SCIP_INVALIDCALL, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiStartStrongbranch(SCIP_LPI *lpi)
LP interface structure
start strong branching - call before any strongbranching
References SCIP_OKAY.
SCIP_RETCODE SCIPlpiEndStrongbranch(SCIP_LPI *lpi)
LP interface structure
end strong branching - call after any strongbranching
References SCIP_OKAY.
static SCIP_RETCODE lpiStrongbranch(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one arbitrary candidate
SCIP_RETCODE SCIPlpiStrongbranchFrac(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one fractional candidate
References SCIP_CALL, SCIP_LPERROR, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchesFrac(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given fractional candidates
References NULL, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchInt(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one candidate with integral value
References SCIP_CALL, SCIP_LPERROR, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchesInt(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given candidates with integral values
References NULL, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY.
SCIP_Bool SCIPlpiWasSolved(SCIP_LPI *lpi)
LP interface structure
returns whether a solve method was called after the last modification of the LP
References NULL.
SCIP_RETCODE SCIPlpiGetSolFeasibility(SCIP_LPI *lpi, SCIP_Bool *primalfeasible, SCIP_Bool *dualfeasible)
LP interface structure
gets information about primal and dual feasibility of the current LP solution
References NULL, SCIP_OKAY, SCIPdebugMessage, SCIPlpiIsDualFeasible, SCIPlpiIsPrimalFeasible.
SCIP_Bool SCIPlpiExistsPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point); this does not necessarily mean, that the solver knows and can return the primal ray
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiHasPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point), and the solver knows and can return the primal ray
References FALSE, NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsPrimalUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal unbounded
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsPrimalInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal infeasible
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsPrimalFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal feasible
References NULL, SCIPdebugMessage.
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiIsOptimal.
SCIP_Bool SCIPlpiExistsDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point); this does not necessarily mean, that the solver knows and can return the dual ray
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiHasDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point), and the solver knows and can return the dual ray
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is dual unbounded
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is dual infeasible
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual feasible
References NULL, SCIPdebugMessage.
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiIsOptimal.
SCIP_Bool SCIPlpiIsOptimal(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP was solved to optimality
References NULL, SCIPdebugMessage, SCIPlpiIsDualFeasible, SCIPlpiIsPrimalFeasible.
Referenced by SCIPlpiIsStable.
SCIP_Bool SCIPlpiIsStable(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff current LP basis is stable
References FALSE, NULL, SCIP_INVALID, SCIP_LPSOLQUALITY_ESTIMCONDITION, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiGetRealSolQuality, SCIPlpiIsObjlimExc, SCIPlpiIsOptimal.
SCIP_Bool SCIPlpiIsObjlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the objective limit was reached
References NULL, SCIPdebugMessage.
Referenced by SCIPlpiIsStable.
SCIP_Bool SCIPlpiIsIterlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the iteration limit was reached
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsTimelimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the time limit was reached
References NULL, SCIPdebugMessage.
int SCIPlpiGetInternalStatus(SCIP_LPI *lpi)
LP interface structure
returns the internal solution status of the solver
References NULL, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiIgnoreInstability(SCIP_LPI *lpi, SCIP_Bool *success)
LP interface structure
tries to reset the internal status of the LP solver in order to ignore an instability of the last solving call
References FALSE, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetObjval(SCIP_LPI *lpi, SCIP_Real *objval)
LP interface structure
gets objective value of solution
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetSol(SCIP_LPI *lpi, SCIP_Real *objval, SCIP_Real *primsol, SCIP_Real *dualsol, SCIP_Real *activity, SCIP_Real *redcost)
LP interface structure
gets primal and dual solution vectors
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetPrimalRay(SCIP_LPI *lpi, SCIP_Real *ray)
LP interface structure
gets primal ray for unbounded LPs
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetDualfarkas(SCIP_LPI *lpi, SCIP_Real *dualfarkas)
LP interface structure
gets dual farkas proof for infeasibility
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetIterations(SCIP_LPI *lpi, int *iterations)
LP interface structure
gets the number of LP iterations of the last solve call
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetRealSolQuality(SCIP_LPI *lpi, SCIP_LPSOLQUALITY qualityindicator, SCIP_Real *quality)
LP interface structure
gets information about the quality of an LP solutionSuch information is usually only available, if also a (maybe not optimal) solution is available. The LPI should return SCIP_INVALID for quality, if the requested quality is not available.
References NULL, SCIP_INVALID, SCIP_INVALIDDATA, SCIP_LPSOLQUALITY_ESTIMCONDITION, SCIP_LPSOLQUALITY_EXACTCONDITION, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage.
Referenced by SCIPlpiIsStable.
static SCIP_RETCODE getRedCostEst(SPxSCIP *spx, int col, SCIP_Real *val)
Return reduced cost of column col if this is readily available, otherwise return 0.0
SCIP_RETCODE SCIPlpiGetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
gets current basis status for columns and rows; arrays must be large enough to store the basis status
References NULL, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
Referenced by SCIPlpiGetState.
SCIP_RETCODE SCIPlpiSetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
sets current basis status for columns and rows
References NULL, SCIP_ALLOC, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_OKAY, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, SOPLEX_TRY.
Referenced by SCIPlpiSetState.
SCIP_RETCODE SCIPlpiGetBasisInd(SCIP_LPI *lpi, int *bind)
LP interface structure
returns the indices of the basic columns and rows; basic column n gives value n, basic row m gives value -1-m
References NULL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiGetBInvRow.
SCIP_RETCODE SCIPlpiGetBInvRow(SCIP_LPI *lpi, int r, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References NULL, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPlpiGetBasisInd, SCIPmessagePrintWarning.
Referenced by SCIPlpiGetBInvARow.
static SCIP_RETCODE lpiGetBInvVec(SCIP_LPI *lpi, SCIP_Real *rhs, SCIP_Real *coef)
LP interface structure
get dense solution of basis matrix B * coef = rhs
SCIP_RETCODE SCIPlpiGetBInvCol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetBInvARow(SCIP_LPI *lpi, int r, const SCIP_Real *binvrow, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References NULL, SCIP_ALLOC, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiGetBInvRow.
SCIP_RETCODE SCIPlpiGetBInvACol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
stores LPi state (like basis information) into lpistate object
References NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SCIPlpiGetBase.
SCIP_RETCODE SCIPlpiSetState(SCIP_LPI *lpi, BMS_BLKMEM *, SCIP_LPISTATE *lpistate)
LP interface structure
loads LPi state (like basis information) into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetState()
References NULL, REALABS, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiIsInfinity, SCIPlpiSetBase.
SCIP_RETCODE SCIPlpiClearState(SCIP_LPI *lpi)
LP interface structure
clears current LPi state (like basis information) of the solver
References NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiFreeState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
frees LPi state information
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_Bool SCIPlpiHasStateBasis(SCIP_LPI *lpi, SCIP_LPISTATE *lpistate)
LP interface structure
checks, whether the given LP state contains simplex basis information
References TRUE.
SCIP_RETCODE SCIPlpiReadState(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LP state (like basis information from a file
References SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiWriteState(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LP state (like basis information) to a file
References SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiGetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
stores LPi pricing norms information
References NULL, SCIP_ALLOC, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS *lpinorms)
LP interface structure
loads LPi pricing norms into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetNorms()
References SCIP_LPiNorms::ncols, SCIP_LPiNorms::norms, SCIP_LPiNorms::nrows, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiFreeNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
frees pricing norms information
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int *ival)
LP interface structure
gets integer parameter of LP
References NULL, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_LPPAR_TIMING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int ival)
LP interface structure
sets integer parameter of LP
References FALSE, NULL, SCIP_LPERROR, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_LPPAR_TIMING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIP_PRICING_AUTO, SCIP_PRICING_DEVEX, SCIP_PRICING_FULL, SCIP_PRICING_LPIDEFAULT, SCIP_PRICING_PARTIAL, SCIP_PRICING_STEEP, SCIP_PRICING_STEEPQSTART, SCIPdebugMessage, TRUE.
Referenced by SCIPlpiCreate.
SCIP_RETCODE SCIPlpiGetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real *dval)
LP interface structure
gets floating point parameter of LP
References NULL, SCIP_LPPAR_CONDITIONLIMIT, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_ROWREPSWITCH, SCIP_LPPAR_UOBJLIM, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real dval)
LP interface structure
sets floating point parameter of LP
References NULL, SCIP_LPPAR_CONDITIONLIMIT, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_ROWREPSWITCH, SCIP_LPPAR_UOBJLIM, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage.
SCIP_Real SCIPlpiInfinity(SCIP_LPI *)
returns value treated as infinity in the LP solver
References SCIPdebugMessage.
Referenced by SCIPlpiCreate.
SCIP_Bool SCIPlpiIsInfinity(SCIP_LPI *, SCIP_Real val)
value to be checked for infinity
checks if given value is treated as infinity in the LP solver
References SCIPdebugMessage.
Referenced by SCIPlpiSetState.
static SCIP_Bool fileExists(const char *filename)
file name
returns, whether the given file exists
SCIP_RETCODE SCIPlpiReadLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LP from a file
References NULL, SCIP_NOFILE, SCIP_OKAY, SCIP_READERROR, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiWriteLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LP to a file
References NULL, SCIP_OKAY, SCIP_WRITEERROR, SCIPdebugMessage, SCIPmessagePrintWarning.
AUTOPRICING_ITERSWITCH
start with devex and switch to steepest edge after this many iterations
STRONGBRANCH_RESTOREBASIS
if defined then in SCIPlpiStrongbranch() we restore the basis after the down branch and after the up branch; if false only after the end of a strong branching phase, which however seems to mostly increase strong branching time and iterations
SOPLEX_SUBVERSION
Referenced by SCIPlpiGetSolverName.
WITH_BOUNDFLIPPING
SOPLEX_VERBLEVEL
verbosity level for LPINFO
NULL
Referenced by SCIPlpiAddCols, SCIPlpiAddRows, SCIPlpiChgBounds, SCIPlpiChgCoef, SCIPlpiChgObj, SCIPlpiChgObjsen, SCIPlpiChgSides, SCIPlpiClear, SCIPlpiClearState, SCIPlpiCreate, SCIPlpiDelCols, SCIPlpiDelColset, SCIPlpiDelRows, SCIPlpiDelRowset, SCIPlpiExistsDualRay, SCIPlpiExistsPrimalRay, SCIPlpiFree, SCIPlpiFreeNorms, SCIPlpiFreeState, SCIPlpiGetBase, SCIPlpiGetBasisInd, SCIPlpiGetBInvACol, SCIPlpiGetBInvARow, SCIPlpiGetBInvCol, SCIPlpiGetBInvRow, SCIPlpiGetBounds, SCIPlpiGetCoef, SCIPlpiGetColNames, SCIPlpiGetCols, SCIPlpiGetDualfarkas, SCIPlpiGetInternalStatus, SCIPlpiGetIntpar, SCIPlpiGetIterations, SCIPlpiGetNCols, SCIPlpiGetNNonz, SCIPlpiGetNorms, SCIPlpiGetNRows, SCIPlpiGetObj, SCIPlpiGetObjsen, SCIPlpiGetObjval, SCIPlpiGetPrimalRay, SCIPlpiGetRealpar, SCIPlpiGetRealSolQuality, SCIPlpiGetRowNames, SCIPlpiGetRows, SCIPlpiGetSides, SCIPlpiGetSol, SCIPlpiGetSolFeasibility, SCIPlpiGetState, SCIPlpiHasDualRay, SCIPlpiHasPrimalRay, SCIPlpiIgnoreInstability, SCIPlpiIsDualFeasible, SCIPlpiIsDualInfeasible, SCIPlpiIsDualUnbounded, SCIPlpiIsIterlimExc, SCIPlpiIsObjlimExc, SCIPlpiIsOptimal, SCIPlpiIsPrimalFeasible, SCIPlpiIsPrimalInfeasible, SCIPlpiIsPrimalUnbounded, SCIPlpiIsStable, SCIPlpiIsTimelimExc, SCIPlpiLoadColLP, SCIPlpiReadLP, SCIPlpiScaleCol, SCIPlpiScaleRow, SCIPlpiSetBase, SCIPlpiSetIntpar, SCIPlpiSetNorms, SCIPlpiSetRealpar, SCIPlpiSetState, SCIPlpiSolveDual, SCIPlpiSolvePrimal, SCIPlpiStrongbranchesFrac, SCIPlpiStrongbranchesInt, SCIPlpiWasSolved, SCIPlpiWriteLP.
SOPLEX_TRY
Macro for a single SoPlex call for which exceptions have to be catched - return an LP error. We make no distinction between different exception types, e.g., between memory allocation and other exceptions.
Referenced by SCIPlpiChgCoef, SCIPlpiChgObjsen, SCIPlpiClear, SCIPlpiCreate, SCIPlpiDelCols, SCIPlpiDelColset, SCIPlpiDelRows, SCIPlpiDelRowset, SCIPlpiReadState, SCIPlpiSetBase, SCIPlpiWriteState.
SOPLEX_TRY_ABORT
COLS_PER_PACKET
ROWS_PER_PACKET
typedef SCIP_DUALPACKET COLPACKET
typedef SCIP_DUALPACKET ROWPACKET
char spxname[100][100]
char spxdesc[200][200]
static SCIP_RETCODE ensureCstatMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes cstat array to have at least num entries
static SCIP_RETCODE ensureRstatMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes rstat array to have at least num entries
static int colpacketNum(int ncols)
number of columns to store
returns the number of packets needed to store column packet information
static int rowpacketNum(int nrows)
number of rows to store
returns the number of packets needed to store row packet information
static void lpistatePack(SCIP_LPISTATE *lpistate, const int *cstat, const int *rstat)
pointer to LPi state data
store row and column basis status in a packed LPi state object
static void lpistateUnpack(const SCIP_LPISTATE *lpistate, int *cstat, int *rstat)
pointer to LPi state data
unpacks row and column basis status from a packed LPi state object
static SCIP_RETCODE lpistateCreate(SCIP_LPISTATE **lpistate, BMS_BLKMEM *blkmem, int ncols, int nrows)
pointer to LPi state
creates LPi state information object
static void lpistateFree(SCIP_LPISTATE **lpistate, BMS_BLKMEM *blkmem)
pointer to LPi state information (like basis information)
frees LPi state information
static SPxLP::SPxSense spxObjsen(SCIP_OBJSEN objsen)
SCIP's objective sense value
converts SCIP's objective sense into SoPlex's objective sense
static void invalidateSolution(SCIP_LPI *lpi)
marks the current LP to be unsolved