lpi_grb.c
const char* SCIPlpiGetSolverName(void)
gets name and version of LP solver
const char* SCIPlpiGetSolverDesc(void)
gets description of LP solver (developer, webpage, ...)
void* SCIPlpiGetSolverPointer(SCIP_LPI *lpi)
pointer to an LP interface structure
gets pointer for LP solver - use only with great careHere we return the pointer to the model.
SCIP_RETCODE SCIPlpiCreate(SCIP_LPI **lpi, SCIP_MESSAGEHDLR *messagehdlr, const char *name, SCIP_OBJSEN objsen)
pointer to an LP interface structure
creates an LP problem object
References CHECK_ZERO, FALSE, NULL, SCIP_ALLOC, SCIP_Bool, SCIP_CALL, SCIP_LPPAR_PRICING, SCIP_OKAY, SCIP_PRICING_LPIDEFAULT, SCIP_Real, SCIPdebugMessage, SCIPlpiChgObjsen, SCIPlpiSetIntpar, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiFree(SCIP_LPI **lpi)
pointer to an LP interface structure
deletes an LP problem object
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiLoadColLP(SCIP_LPI *lpi, SCIP_OBJSEN objsen, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **colnames, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **rownames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
copies LP data with column matrix into LP solver
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIP_Real, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiAddCols(SCIP_LPI *lpi, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **colnames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds columns to the LP
References CHECK_ZERO, NULL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiDelCols(SCIP_LPI *lpi, int firstcol, int lastcol)
LP interface structure
deletes all columns in the given range from LP
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiDelColset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes columns from SCIP_LP; the new position of a column must not be greater that its old position
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiAddRows(SCIP_LPI *lpi, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **rownames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds rows to the LP
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiDelRows(SCIP_LPI *lpi, int firstrow, int lastrow)
LP interface structure
deletes all rows in the given range from LP
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiDelRowset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes rows from SCIP_LP; the new position of a row must not be greater that its old position
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiClear(SCIP_LPI *lpi)
LP interface structure
clears the whole LP
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiChgBounds(SCIP_LPI *lpi, int ncols, const int *ind, const SCIP_Real *lb, const SCIP_Real *ub)
LP interface structure
changes lower and upper bounds of columns
References CHECK_ZERO, NULL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPdebugPrintf.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiChgSides(SCIP_LPI *lpi, int nrows, const int *ind, const SCIP_Real *lhs, const SCIP_Real *rhs)
LP interface structure
changes left and right hand sides of rows
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiChgCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real newval)
LP interface structure
changes a single coefficient
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleCol, SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiChgObjsen(SCIP_LPI *lpi, SCIP_OBJSEN objsen)
LP interface structure
changes the objective sense
References CHECK_ZERO, NULL, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiCreate.
SCIP_RETCODE SCIPlpiChgObj(SCIP_LPI *lpi, int ncols, int *ind, SCIP_Real *obj)
LP interface structure
changes objective values of columns in the LP
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiScaleRow(SCIP_LPI *lpi, int row, SCIP_Real scaleval)
LP interface structure
multiplies a row with a non-zero scalar; for negative scalars, the row's sense is switched accordingly
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiChgCoef, SCIPlpiChgSides, SCIPlpiGetRows.
SCIP_RETCODE SCIPlpiScaleCol(SCIP_LPI *lpi, int col, SCIP_Real scaleval)
LP interface structure
multiplies a column with a non-zero scalar; the objective value is multiplied with the scalar, and the bounds are divided by the scalar; for negative scalars, the column's bounds are switched
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiChgBounds, SCIPlpiChgCoef, SCIPlpiChgObj, SCIPlpiGetCols, SCIPlpiGetObj.
SCIP_RETCODE SCIPlpiGetNRows(SCIP_LPI *lpi, int *nrows)
LP interface structure
gets the number of rows in the LP
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNCols(SCIP_LPI *lpi, int *ncols)
LP interface structure
gets the number of columns in the LP
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNNonz(SCIP_LPI *lpi, int *nnonz)
LP interface structure
gets the number of nonzero elements in the LP constraint matrix
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetCols(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lb, SCIP_Real *ub, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets columns from LP problem object; the arrays have to be large enough to store all values Either both, lb and ub, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiGetRows(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhs, SCIP_Real *rhs, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets rows from LP problem object; the arrays have to be large enough to store all values. Either both, lhs and rhs, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiGetColNames(SCIP_LPI *lpi, int firstcol, int lastcol, char **colnames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets column names
References SCIP_LPERROR, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetRowNames(SCIP_LPI *lpi, int firstrow, int lastrow, char **rownames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets row names
References SCIP_LPERROR, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetObjsen(SCIP_LPI *lpi, SCIP_OBJSEN *objsen)
LP interface structure
gets the objective sense of the LP
References CHECK_ZERO, NULL, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetObj(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *vals)
LP interface structure
gets objective coefficients from LP problem object
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiGetBounds(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lbs, SCIP_Real *ubs)
LP interface structure
gets current bounds from LP problem object
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetSides(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhss, SCIP_Real *rhss)
LP interface structure
gets current row sides from LP problem object
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real *val)
LP interface structure
gets a single coefficient
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSolvePrimal(SCIP_LPI *lpi)
LP interface structure
calls primal simplex to solve the LP
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_PRIMAL, NULL, SCIP_CALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage, TRUE.
SCIP_RETCODE SCIPlpiSolveDual(SCIP_LPI *lpi)
LP interface structure
calls dual simplex to solve the LP
References CHECK_ZERO, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIP_CALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage, TRUE.
SCIP_RETCODE SCIPlpiSolveBarrier(SCIP_LPI *lpi, SCIP_Bool crossover)
LP interface structure
calls barrier or interior point algorithm to solve the LP with crossover to simplex basis
References CHECK_ZERO, GRB_INT_PAR_METHOD, NULL, SCIP_CALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiStartStrongbranch(SCIP_LPI *lpi)
LP interface structure
start strong branching - call before any strong branching
References SCIP_OKAY.
SCIP_RETCODE SCIPlpiEndStrongbranch(SCIP_LPI *lpi)
LP interface structure
end strong branching - call after any strong branching
References SCIP_OKAY.
static SCIP_RETCODE lpiStrongbranch(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one candidate
SCIP_RETCODE SCIPlpiStrongbranchFrac(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one fractional candidate
References SCIP_CALL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchesFrac(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given fractional candidates
References NULL, SCIP_CALL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchInt(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one candidate with integral value
References SCIP_CALL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchesInt(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given candidates with integral values
References NULL, SCIP_CALL, SCIP_OKAY.
SCIP_Bool SCIPlpiWasSolved(SCIP_LPI *lpi)
LP interface structure
returns whether a solve method was called after the last modification of the LP
References NULL.
SCIP_RETCODE SCIPlpiGetSolFeasibility(SCIP_LPI *lpi, SCIP_Bool *primalfeasible, SCIP_Bool *dualfeasible)
LP interface structure
gets information about primal and dual feasibility of the current LP solution
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, GRB_METHOD_PRIMAL, NULL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, TRUE.
Referenced by SCIPlpiIsPrimalUnbounded.
SCIP_Bool SCIPlpiExistsPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point); this does not necessarily mean, that the solver knows and can return the primal ray
References NULL.
SCIP_Bool SCIPlpiHasPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point), and the solver knows and can return the primal ray
References NULL.
SCIP_Bool SCIPlpiIsPrimalUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal unbounded
References FALSE, NULL, SCIP_Bool, SCIP_OKAY, SCIPdebugMessage, SCIPlpiGetSolFeasibility.
SCIP_Bool SCIPlpiIsPrimalInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal infeasible
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsPrimalFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal feasible
References CHECK_ZERO, GRB_INT_PAR_METHOD, GRB_METHOD_PRIMAL, NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiExistsDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point); this does not necessarily mean, that the solver knows and can return the dual ray
References NULL.
SCIP_Bool SCIPlpiHasDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point), and the solver knows and can return the dual ray
References CHECK_ZERO, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL.
SCIP_Bool SCIPlpiIsDualUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual unbounded
References CHECK_ZERO, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual infeasible
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual feasible
References CHECK_ZERO, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsOptimal(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP was solved to optimality
References NULL.
SCIP_Bool SCIPlpiIsStable(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff current LP basis is stable
References NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsObjlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the objective limit was reached
References NULL.
SCIP_Bool SCIPlpiIsIterlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the iteration limit was reached
References NULL.
SCIP_Bool SCIPlpiIsTimelimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the time limit was reached
References NULL.
int SCIPlpiGetInternalStatus(SCIP_LPI *lpi)
LP interface structure
returns the internal solution status of the solver
References NULL.
SCIP_RETCODE SCIPlpiIgnoreInstability(SCIP_LPI *lpi, SCIP_Bool *success)
LP interface structure
tries to reset the internal status of the LP solver in order to ignore an instability of the last solving call
References FALSE, NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiGetObjval(SCIP_LPI *lpi, SCIP_Real *objval)
LP interface structure
gets objective value of solutionif the solution status is iteration limit reached (GRB_ITERATION_LIMIT), the objective value was not computed
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetSol(SCIP_LPI *lpi, SCIP_Real *objval, SCIP_Real *primsol, SCIP_Real *dualsol, SCIP_Real *activity, SCIP_Real *redcost)
LP interface structure
gets primal and dual solution vectors
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_INVALIDDATA, SCIP_OKAY, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetPrimalRay(SCIP_LPI *lpi, SCIP_Real *ray)
LP interface structure
gets primal ray for unbounded LPs
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetDualfarkas(SCIP_LPI *lpi, SCIP_Real *dualfarkas)
LP interface structure
gets dual Farkas proof for infeasibility
References CHECK_ZERO, NULL, SCIP_LPERROR, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetIterations(SCIP_LPI *lpi, int *iterations)
LP interface structure
gets the number of LP iterations of the last solve call
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiGetRealSolQuality(SCIP_LPI *lpi, SCIP_LPSOLQUALITY qualityindicator, SCIP_Real *quality)
LP interface structure
gets information about the quality of an LP solutionSuch information is usually only available, if also a (maybe not optimal) solution is available. The LPI should return SCIP_INVALID for quality, if the requested quantity is not available.
References CHECK_ZERO, NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiGetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
gets current basis status for columns and rows; arrays must be large enough to store the basis status
References CHECK_ZERO, NULL, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_INVALIDDATA, SCIP_OKAY, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiSetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
sets current basis status for columns and rows
References CHECK_ZERO, NULL, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_INVALIDDATA, SCIP_OKAY, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetBasisInd(SCIP_LPI *lpi, int *bind)
LP interface structure
returns the indices of the basic columns and rows; basic column n gives value n, basic row m gives value -1-m
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL_QUIET, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetBInvRow(SCIP_LPI *lpi, int r, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL_QUIET, SCIP_OKAY, SCIPdebugMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetBInvCol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL_QUIET, SCIP_OKAY, SCIPdebugMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetBInvARow(SCIP_LPI *lpi, int r, const SCIP_Real *binvrow, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL_QUIET, SCIP_OKAY, SCIPdebugMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetBInvACol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_CALL_QUIET, SCIP_OKAY, SCIPdebugMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
stores LPi state (like basis information) into lpistate object
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_Bool, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE *lpistate)
LP interface structure
loads LPi state (like basis information) into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetState()
References CHECK_ZERO, NULL, REALABS, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiIsInfinity.
SCIP_RETCODE SCIPlpiClearState(SCIP_LPI *lpi)
LP interface structure
clears current LPi state (like basis information) of the solver
References CHECK_ZERO, NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiFreeState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
frees LPi state information
References NULL, SCIP_OKAY.
SCIP_Bool SCIPlpiHasStateBasis(SCIP_LPI *lpi, SCIP_LPISTATE *lpistate)
LP interface structure
checks, whether the given LP state contains simplex basis information
References NULL.
SCIP_RETCODE SCIPlpiReadState(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LP state (like basis information from a file
References CHECK_ZERO, NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiWriteState(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LP state (like basis information) to a file
References CHECK_ZERO, NULL, SCIP_MAXSTRLEN, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
stores LPi pricing norms information
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiSetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS *lpinorms)
LP interface structure
loads LPi pricing norms into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetNorms()
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiFreeNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
frees pricing norms information
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiGetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int *ival)
LP interface structure
gets integer parameter of LP
References FALSE, NULL, SCIP_CALL, SCIP_LPPAR_FASTMIP, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIP_Real, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiSetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int ival)
LP interface structure
sets integer parameter of LP
References FALSE, NULL, SCIP_Bool, SCIP_CALL, SCIP_LPERROR, SCIP_LPPAR_FASTMIP, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIP_PRICING_AUTO, SCIP_PRICING_DEVEX, SCIP_PRICING_FULL, SCIP_PRICING_LPIDEFAULT, SCIP_PRICING_PARTIAL, SCIP_PRICING_STEEP, SCIP_PRICING_STEEPQSTART, SCIPdebugMessage, TRUE.
Referenced by SCIPlpiCreate.
SCIP_RETCODE SCIPlpiGetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real *dval)
LP interface structure
gets floating point parameter of LP
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_LPPAR_BARRIERCONVTOL, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_MARKOWITZ, SCIP_LPPAR_UOBJLIM, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real dval)
LP interface structure
sets floating point parameter of LP
References CHECK_ZERO, NULL, SCIP_CALL, SCIP_LPPAR_BARRIERCONVTOL, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_MARKOWITZ, SCIP_LPPAR_UOBJLIM, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage.
SCIP_Real SCIPlpiInfinity(SCIP_LPI *lpi)
LP interface structure
returns value treated as infinity in the LP solver
SCIP_Bool SCIPlpiIsInfinity(SCIP_LPI *lpi, SCIP_Real val)
LP interface structure
checks if given value is treated as infinity in the LP solver
Referenced by SCIPlpiSetState.
SCIP_RETCODE SCIPlpiReadLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LP from a file
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiWriteLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LP to a file
References CHECK_ZERO, NULL, SCIP_OKAY, SCIPdebugMessage.
CHECK_ZERO
Referenced by SCIPlpiAddCols, SCIPlpiAddRows, SCIPlpiChgBounds, SCIPlpiChgCoef, SCIPlpiChgObj, SCIPlpiChgObjsen, SCIPlpiChgSides, SCIPlpiClear, SCIPlpiClearState, SCIPlpiCreate, SCIPlpiDelCols, SCIPlpiDelColset, SCIPlpiDelRows, SCIPlpiDelRowset, SCIPlpiFree, SCIPlpiGetBase, SCIPlpiGetBasisInd, SCIPlpiGetBInvACol, SCIPlpiGetBInvARow, SCIPlpiGetBInvCol, SCIPlpiGetBInvRow, SCIPlpiGetBounds, SCIPlpiGetCoef, SCIPlpiGetCols, SCIPlpiGetDualfarkas, SCIPlpiGetNCols, SCIPlpiGetNNonz, SCIPlpiGetNRows, SCIPlpiGetObj, SCIPlpiGetObjsen, SCIPlpiGetObjval, SCIPlpiGetPrimalRay, SCIPlpiGetRealpar, SCIPlpiGetRealSolQuality, SCIPlpiGetRows, SCIPlpiGetSides, SCIPlpiGetSol, SCIPlpiGetSolFeasibility, SCIPlpiGetState, SCIPlpiHasDualRay, SCIPlpiIsDualFeasible, SCIPlpiIsDualUnbounded, SCIPlpiIsPrimalFeasible, SCIPlpiLoadColLP, SCIPlpiReadLP, SCIPlpiReadState, SCIPlpiScaleCol, SCIPlpiScaleRow, SCIPlpiSetBase, SCIPlpiSetRealpar, SCIPlpiSetState, SCIPlpiSolveBarrier, SCIPlpiSolveDual, SCIPlpiSolvePrimal, SCIPlpiWriteLP, SCIPlpiWriteState.
SVECTOR
Referenced by SCIPlpiGetBInvACol, SCIPlpiGetBInvARow, SCIPlpiGetBInvCol, SCIPlpiGetBInvRow.
GRB_METHOD_DUAL
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiHasDualRay, SCIPlpiIsDualFeasible, SCIPlpiIsDualUnbounded, SCIPlpiSolveDual.
GRB_METHOD_PRIMAL
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiIsPrimalFeasible, SCIPlpiSolvePrimal.
GRB_INT_PAR_METHOD
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiHasDualRay, SCIPlpiIsDualFeasible, SCIPlpiIsDualUnbounded, SCIPlpiIsPrimalFeasible, SCIPlpiSolveBarrier, SCIPlpiSolveDual, SCIPlpiSolvePrimal.
SCIP_SINGLEPACKETSIZE
each entry needs one bit of information
SCIP_DUALPACKETSIZE
each entry needs two bits of information
COLS_PER_PACKET
ROWS_PER_PACKET
GRB_REFACTORMAXITERS
NUMINTPARAM
NUMDBLPARAM
typedef unsigned int SCIP_SINGLEPACKET
storing single bits in packed format
typedef unsigned int SCIP_DUALPACKET
storing bit pairs in packed format
typedef SCIP_DUALPACKET COLPACKET
typedef SCIP_DUALPACKET ROWPACKET
typedef struct GRBParam GRBPARAM
unsigned char warnedbeta
const char* intparam[NUMINTPARAM][NUMINTPARAM]
const char* dblparam[NUMDBLPARAM][NUMDBLPARAM]
const double dblparammin[NUMDBLPARAM][NUMDBLPARAM]
GRBenv* grbenv
Gurobi environment (only needed for initialization)
int numlp
number of open LP objects
char grbname[100][100]
static SCIP_RETCODE ensureSidechgMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes senarray to have at least num entries
static SCIP_RETCODE ensureValMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes valarray and indarray to have at least num entries
static SCIP_RETCODE ensureCstatMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes cstat array to have at least num entries
static SCIP_RETCODE ensureRstatMem(SCIP_LPI *lpi, int num)
LP interface structure
resizes rstat array to have at least num entries
static SCIP_RETCODE getBase(SCIP_LPI *lpi, SCIP_Bool *success)
LP interface structure
stores current basis in internal arrays of LPI data structure
static SCIP_RETCODE setBase(SCIP_LPI *lpi)
LP interface structure
loads basis stored in internal arrays of LPI data structure into Gurobi
static int colpacketNum(int ncols)
number of columns to store
returns the number of packets needed to store column packet information
static int rowpacketNum(int nrows)
number of rows to store
returns the number of packets needed to store row packet information
static void SCIPencodeDualBitNeg(const int *inp, SCIP_DUALPACKET *out, int count)
unpacked input vector
encode a negated dual bit vector into packed format
static void SCIPdecodeDualBitNeg(const SCIP_DUALPACKET *inp, int *out, int count)
packed input vector
decode a packed dual bit vector into negated unpacked format
static void lpistatePack(SCIP_LPISTATE *lpistate, const int *cstat, const int *rstat)
pointer to LPi state data
store row and column basis status in a packed LPi state object
static void lpistateUnpack(const SCIP_LPISTATE *lpistate, int *cstat, int *rstat)
pointer to LPi state data
unpacks row and column basis status from a packed LPi state object
static SCIP_RETCODE lpistateCreate(SCIP_LPISTATE **lpistate, BMS_BLKMEM *blkmem, int ncols, int nrows)
pointer to LPi state
creates LPi state information object
static void lpistateFree(SCIP_LPISTATE **lpistate, BMS_BLKMEM *blkmem)
pointer to LPi state information (like basis information)
frees LPi state information
static SCIP_RETCODE getParameterValues(SCIP_LPI *lpi, GRBPARAM *grbparam)
LP interface structure
gets all Gurobi parameters used in LPI
static SCIP_RETCODE checkParameterValues(SCIP_LPI *lpi)
LP interface structure
in debug mode, checks validity of Gurobi parameters
static SCIP_RETCODE setParameterValues(SCIP_LPI *lpi, GRBPARAM *grbparam)
LP interface structure
sets all Gurobi parameters used in LPI
static void copyParameterValues(GRBPARAM *dest, const GRBPARAM *source)
destination Gurobi parameters
copies Gurobi parameters from source to dest
static SCIP_RETCODE getIntParam(SCIP_LPI *lpi, const char *param, int *p)
LP interface structure
gets a single integer parameter value
static SCIP_RETCODE setIntParam(SCIP_LPI *lpi, const char *param, int parval)
LP interface structure
sets a single integer parameter value
static SCIP_RETCODE getDblParam(SCIP_LPI *lpi, const char *param, double *p)
gets a single double parameter value
static SCIP_RETCODE setDblParam(SCIP_LPI *lpi, const char *param, double parval)
LP interface structure
sets a single double parameter value
static void invalidateSolution(SCIP_LPI *lpi)
LP interface structure
marks the current LP to be unsolved
static SCIP_RETCODE convertSides(SCIP_LPI *lpi, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, int *rngcount)
LP interface structure
converts SCIP's lhs/rhs pairs into Gurobi's sen/rhs
static SCIP_RETCODE reconvertBothSides(SCIP_LPI *lpi, int nrows, SCIP_Real *lhs, SCIP_Real *rhs)
LP interface structure
converts Gurobi's sen/rhs pairs into SCIP's lhs/rhs pairs
static SCIP_RETCODE reconvertLhs(SCIP_LPI *lpi, int nrows, SCIP_Real *lhs)
LP interface structure
converts Gurobi's sen/rhs pairs into SCIP's lhs/rhs pairs, only storing the left hand side
static SCIP_RETCODE reconvertRhs(SCIP_LPI *lpi, int nrows, SCIP_Real *rhs)
LP interface structure
converts Gurobi's sen/rhs pairs into SCIP's lhs/rhs pairs, only storing the right hand side
static SCIP_RETCODE reconvertSides(SCIP_LPI *lpi, int nrows, SCIP_Real *lhs, SCIP_Real *rhs)
LP interface structure
converts Gurobi's sen/rhs pairs into SCIP's lhs/rhs pairs
static SCIP_RETCODE restoreLPData(SCIP_LPI *lpi)
LP interface structure
after restoring old LP data, need to resolve the LP to be able to retrieve correct information