lpi.h
const char* SCIPlpiGetSolverName(void)
gets name and version of LP solver
References CLP_VERSION, CPX_SUBVERSION, LPINAME, MIN, SCIP_Real, SCIPdebugMessage, SOPLEX_SUBVERSION.
const char* SCIPlpiGetSolverDesc(void)
gets description of LP solver (developer, webpage, ...)
void* SCIPlpiGetSolverPointer(SCIP_LPI *lpi)
pointer to an LP interface structure
gets pointer for LP solver - use only with great careThe behavior of this function depends on the solver and its use is therefore only recommended if you really know what you are doing. In general, it returns a pointer to the LP solver object.gets pointer for LP solver - use only with great caregets pointer for LP solver - use only with great careHere we return the pointer to the LP environment.gets pointer for LP solver - use only with great careHere we return the pointer to the model.
References NULL.
SCIP_RETCODE SCIPlpiCreate(SCIP_LPI **lpi, SCIP_MESSAGEHDLR *messagehdlr, const char *name, SCIP_OBJSEN objsen)
pointer to an LP interface structure
creates an LP problem objectcreates an LP problem object SCIP_OK on success
References CHECK_ZERO, DEGEN_LEVEL, FALSE, MOSEK_CALL, NULL, SCIP_ALLOC, SCIP_Bool, SCIP_CALL, SCIP_LPERROR, SCIP_LPPAR_PRICING, SCIP_OKAY, SCIP_PRICING_LPIDEFAULT, SCIP_Real, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiChgObjsen, SCIPlpiInfinity, SCIPlpiSetIntpar, SCIPmessagePrintWarning, SENSE2MOSEK, SETBACK_LIMIT, SOPLEX_TRY, SOPLEX_VERBLEVEL, TRUE.
SCIP_RETCODE SCIPlpiFree(SCIP_LPI **lpi)
pointer to an LP interface structure
deletes an LP problem object
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiLoadColLP(SCIP_LPI *lpi, SCIP_OBJSEN objsen, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **colnames, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **rownames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
copies LP data with column matrix into LP solver
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiAddCols, SCIPlpiChgObjsen, SCIPlpiClear, SCIPmessagePrintWarning, SENSE2MOSEK.
SCIP_RETCODE SCIPlpiAddCols(SCIP_LPI *lpi, int ncols, const SCIP_Real *obj, const SCIP_Real *lb, const SCIP_Real *ub, char **colnames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds columns to the LPind array is not checked for duplicates, problems may appear if indeces are added more than once adds columns to the LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPmessagePrintWarning.
Referenced by SCIPlpiLoadColLP.
SCIP_RETCODE SCIPlpiDelCols(SCIP_LPI *lpi, int firstcol, int lastcol)
LP interface structure
deletes all columns in the given range from LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
Referenced by SCIPlpiClear.
SCIP_RETCODE SCIPlpiDelColset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes columns from SCIP_LPI; the new position of a column must not be greater that its old positiondeletes columns from SCIP_LP; the new position of a column must not be greater that its old position
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiAddRows(SCIP_LPI *lpi, int nrows, const SCIP_Real *lhs, const SCIP_Real *rhs, char **rownames, int nnonz, const int *beg, const int *ind, const SCIP_Real *val)
LP interface structure
adds rows to the LPind array is not checked for duplicates, problems may appear if indeces are added more than once adds rows to the LP
References CHECK_ZERO, FALSE, MOSEK_CALL, NULL, QS_ERROR, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_LPPAR_SCALING, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiSetIntpar, SCIPmessagePrintWarning, TRUE.
SCIP_RETCODE SCIPlpiDelRows(SCIP_LPI *lpi, int firstrow, int lastrow)
LP interface structure
deletes all rows in the given range from LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
Referenced by SCIPlpiClear.
SCIP_RETCODE SCIPlpiDelRowset(SCIP_LPI *lpi, int *dstat)
LP interface structure
deletes rows from SCIP_LPI; the new position of a row must not be greater that its old positiondeletes rows from SCIP_LP; the new position of a row must not be greater that its old position
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiClear(SCIP_LPI *lpi)
LP interface structure
clears the whole LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SCIPlpiDelCols, SCIPlpiDelRows, SOPLEX_TRY.
Referenced by SCIPlpiLoadColLP.
SCIP_RETCODE SCIPlpiChgBounds(SCIP_LPI *lpi, int ncols, const int *ind, const SCIP_Real *lb, const SCIP_Real *ub)
LP interface structure
changes lower and upper bounds of columns
References CHECK_ZERO, CPX_MAGICZEROCONSTANT, EPSZ, MOSEK_CALL, NULL, QS_CONDRET, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPdebugPrintf, SCIPmessagePrintWarning.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiChgSides(SCIP_LPI *lpi, int nrows, const int *ind, const SCIP_Real *lhs, const SCIP_Real *rhs)
LP interface structure
changes left and right hand sides of rows
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
Referenced by SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiChgCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real newval)
LP interface structure
changes a single coefficient
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_OKAY, SCIPdebugMessage, SOPLEX_TRY.
Referenced by SCIPlpiScaleCol, SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiChgObjsen(SCIP_LPI *lpi, SCIP_OBJSEN objsen)
LP interface structure
changes the objective sense
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIPdebugMessage, SENSE2MOSEK, SOPLEX_TRY.
Referenced by SCIPlpiCreate, SCIPlpiLoadColLP.
SCIP_RETCODE SCIPlpiChgObj(SCIP_LPI *lpi, int ncols, int *ind, SCIP_Real *obj)
LP interface structure
changes objective values of columns in the LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPmessagePrintWarning.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiScaleRow(SCIP_LPI *lpi, int row, SCIP_Real scaleval)
LP interface structure
multiplies a row with a non-zero scalar; for negative scalars, the row's sense is switched accordingly
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, QS_TESTG, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiChgCoef, SCIPlpiChgSides, SCIPlpiGetRows, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiScaleCol(SCIP_LPI *lpi, int col, SCIP_Real scaleval)
LP interface structure
multiplies a column with a non-zero scalar; the objective value is multiplied with the scalar, and the bounds are divided by the scalar; for negative scalars, the column's bounds are switched
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, QS_TESTG, SCIP_ALLOC, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_Real, SCIPdebugMessage, SCIPlpiChgBounds, SCIPlpiChgCoef, SCIPlpiChgObj, SCIPlpiGetCols, SCIPlpiGetObj, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetNRows(SCIP_LPI *lpi, int *nrows)
LP interface structure
gets the number of rows in the LP
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetNCols(SCIP_LPI *lpi, int *ncols)
LP interface structure
gets the number of columns in the LP
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetObjsen(SCIP_LPI *lpi, SCIP_OBJSEN *objsen)
LP interface structure
gets the objective sense of the LPgets objective sense of the LP
References CHECK_ZERO, NULL, SCIP_LPERROR, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetNNonz(SCIP_LPI *lpi, int *nnonz)
LP interface structure
gets the number of nonzero elements in the LP constraint matrix
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
Referenced by SCIPlpiGetCols, SCIPlpiGetRows.
SCIP_RETCODE SCIPlpiGetCols(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lb, SCIP_Real *ub, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets columns from LP problem object; the arrays have to be large enough to store all values; Either both, lb and ub, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.gets columns from LP problem object; the arrays have to be large enough to store all values Either both, lb and ub, have to be 0, or both have to be non-0, either nnonz, beg, ind, and val have to be 0, or all of them have to be non-0.gets columns from LP problem object; the arrays have to be large enough to store all values Either both, lb and ub, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.
References CHECK_ZERO, NULL, QS_RETURN, QS_TESTG, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPlpiGetBounds, SCIPlpiGetNNonz.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiGetRows(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhs, SCIP_Real *rhs, int *nnonz, int *beg, int *ind, SCIP_Real *val)
LP interface structure
gets rows from LP problem object; the arrays have to be large enough to store all values. Either both, lhs and rhs, have to be NULL, or both have to be non-NULL, either nnonz, beg, ind, and val have to be NULL, or all of them have to be non-NULL.gets rows from LP problem object; the arrays have to be large enough to store all values. Either both, lhs and rhs, have to be 0, or both have to be non-0, either nnonz, beg, ind, and val have to be 0, or all of them have to be non-0.
References CHECK_ZERO, NULL, QS_RETURN, QS_TESTG, SCIP_CALL, SCIP_INVALIDDATA, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiGetNNonz, SCIPlpiGetSides.
Referenced by SCIPlpiScaleRow.
SCIP_RETCODE SCIPlpiGetColNames(SCIP_LPI *lpi, int firstcol, int lastcol, char **colnames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets column names
References CHECK_ZERO, NULL, QS_ERROR, SCIP_ALLOC, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetRowNames(SCIP_LPI *lpi, int firstrow, int lastrow, char **rownames, char *namestorage, int namestoragesize, int *storageleft)
LP interface structure
gets row names
References CHECK_ZERO, NULL, QS_ERROR, SCIP_ALLOC, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage.
SCIP_RETCODE SCIPlpiGetObj(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *vals)
LP interface structure
gets objective coefficients from LP problem object
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
Referenced by SCIPlpiScaleCol.
SCIP_RETCODE SCIPlpiGetBounds(SCIP_LPI *lpi, int firstcol, int lastcol, SCIP_Real *lbs, SCIP_Real *ubs)
LP interface structure
gets current bounds from LP problem object
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
Referenced by SCIPlpiGetCols.
SCIP_RETCODE SCIPlpiGetSides(SCIP_LPI *lpi, int firstrow, int lastrow, SCIP_Real *lhss, SCIP_Real *rhss)
LP interface structure
gets current row sides from LP problem object
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, QS_TESTG, SCIP_CALL, SCIP_INVALIDDATA, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
Referenced by SCIPlpiGetRows.
SCIP_RETCODE SCIPlpiGetCoef(SCIP_LPI *lpi, int row, int col, SCIP_Real *val)
LP interface structure
gets a single coefficient
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSolvePrimal(SCIP_LPI *lpi)
LP interface structure
calls primal simplex to solve the LPcalls primal simplex to solve the LP
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_PRIMAL, MOSEK_CALL, NULL, QS_RETURN, SCIP_Bool, SCIP_CALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiWriteLP, SCIPlpiWriteState, TRUE, WRITE_ABOVE.
SCIP_RETCODE SCIPlpiSolveDual(SCIP_LPI *lpi)
LP interface structure
calls dual simplex to solve the LPcalls dual simplex to solve the LP
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, MOSEK_CALL, NULL, QS_RETURN, SCIP_Bool, SCIP_CALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiGetObjval, SCIPlpiIsObjlimExc, SCIPlpiWriteLP, SCIPlpiWriteState, TRUE, WRITE_ABOVE.
Referenced by SCIPlpiSolveBarrier.
SCIP_RETCODE SCIPlpiSolveBarrier(SCIP_LPI *lpi, SCIP_Bool crossover)
LP interface structure
calls barrier or interior point algorithm to solve the LP with crossover to simplex basis
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, MOSEK_CALL, NULL, SCIP_CALL, SCIP_INVALIDCALL, SCIP_LPERROR, SCIP_NOMEMORY, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiSolveDual, TRUE, WRITE_ABOVE.
SCIP_RETCODE SCIPlpiStartStrongbranch(SCIP_LPI *lpi)
LP interface structure
start strong branching - call before any strong branchingstart strong branching - call before any strongbranchingstart strong branching
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiEndStrongbranch(SCIP_LPI *lpi)
LP interface structure
end strong branching - call after any strong branchingend strong branching - call after any strongbranchingend strong branching
References NULL, SCIP_OKAY.
SCIP_RETCODE SCIPlpiStrongbranchFrac(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one fractional candidate
References CHECK_ZERO, EPSISINT, FALSE, NULL, QS_CONDRET, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiStrongbranchesFrac(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given fractional candidates
References CHECK_ZERO, EPSISINT, FALSE, NULL, QS_CONDRET, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiStrongbranchInt(SCIP_LPI *lpi, int col, SCIP_Real psol, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on one candidate with integral value
References EPSISINT, NULL, QS_CONDRET, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiStrongbranchesInt(SCIP_LPI *lpi, int *cols, int ncols, SCIP_Real *psols, int itlim, SCIP_Real *down, SCIP_Real *up, SCIP_Bool *downvalid, SCIP_Bool *upvalid, int *iter)
LP interface structure
performs strong branching iterations on given candidates with integral values
References EPSISINT, NULL, QS_CONDRET, SCIP_CALL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, TRUE.
SCIP_Bool SCIPlpiWasSolved(SCIP_LPI *lpi)
LP interface structure
returns whether a solve method was called after the last modification of the LP
References FALSE, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetSolFeasibility(SCIP_LPI *lpi, SCIP_Bool *primalfeasible, SCIP_Bool *dualfeasible)
LP interface structure
gets information about primal and dual feasibility of the current LP solutiongets information about primal and dual feasibility of the current LP solutionhere "true" should mean feasible, "false" should mean unknown
References CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, GRB_METHOD_PRIMAL, MOSEK_CALL, NULL, SCIP_Bool, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, SCIPlpiIsDualFeasible, SCIPlpiIsPrimalFeasible, SUMINFEASBOUND, TRUE, XPRS_LP_OPTIMAL_SCALEDINFEAS.
Referenced by SCIPlpiIsPrimalUnbounded.
SCIP_Bool SCIPlpiExistsPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point); this does not necessarily mean, that the solver knows and can return the primal ray
References FALSE, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage.
Referenced by SCIPlpiIsDualInfeasible.
SCIP_Bool SCIPlpiHasPrimalRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a primal unbounded ray (but not necessary a primal feasible point), and the solver knows and can return the primal ray
References ABORT_ZERO, FALSE, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsPrimalUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal unboundedreturns TRUE iff LP is proven to be primal feasible and unbounded
References ABORT_ZERO, FALSE, NULL, SCIP_Bool, SCIP_OKAY, SCIPdebugMessage, SCIPlpiGetSolFeasibility.
SCIP_Bool SCIPlpiIsPrimalInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal infeasible
References ABORT_ZERO, FALSE, NULL, SCIPdebugMessage, SCIPlpiExistsDualRay.
SCIP_Bool SCIPlpiIsPrimalFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be primal feasible
References ABORT_ZERO, CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_PRIMAL, NULL, SCIP_ABORT_FALSE, SCIP_Bool, SCIPdebugMessage, XPRS_LP_OPTIMAL_SCALEDINFEAS.
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiIsOptimal.
SCIP_Bool SCIPlpiExistsDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point); this does not necessarily mean, that the solver knows and can return the dual ray
References FALSE, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage.
Referenced by SCIPlpiGetState, SCIPlpiIsPrimalInfeasible.
SCIP_Bool SCIPlpiHasDualRay(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to have a dual unbounded ray (but not necessary a dual feasible point), and the solver knows and can return the dual ray
References ABORT_ZERO, CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage, TRUE.
SCIP_Bool SCIPlpiIsDualUnbounded(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual unboundedreturns TRUE iff LP is dual unbounded
References ABORT_ZERO, CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIPdebugMessage.
SCIP_Bool SCIPlpiIsDualInfeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual infeasiblereturns TRUE iff LP is dual infeasible
References ABORT_ZERO, FALSE, NULL, SCIPdebugMessage, SCIPlpiExistsPrimalRay.
SCIP_Bool SCIPlpiIsDualFeasible(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP is proven to be dual feasible
References ABORT_ZERO, CHECK_ZERO, FALSE, GRB_INT_PAR_METHOD, GRB_METHOD_DUAL, NULL, SCIP_ABORT_FALSE, SCIP_Bool, SCIPdebugMessage, XPRS_LP_OPTIMAL_SCALEDINFEAS.
Referenced by SCIPlpiGetSolFeasibility, SCIPlpiIsOptimal.
SCIP_Bool SCIPlpiIsOptimal(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff LP was solved to optimality
References FALSE, NULL, SCIP_ABORT_FALSE, SCIPdebugMessage, SCIPlpiIsDualFeasible, SCIPlpiIsObjlimExc, SCIPlpiIsPrimalFeasible, XPRS_LP_OPTIMAL_SCALEDINFEAS.
Referenced by SCIPlpiIsStable.
SCIP_Bool SCIPlpiIsStable(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff current LP basis is stable
References ABORT_ZERO, FALSE, NULL, SCIP_INVALID, SCIP_LPSOLQUALITY_ESTIMCONDITION, SCIP_OKAY, SCIP_Real, SCIPABORT, SCIPdebugMessage, SCIPlpiGetRealSolQuality, SCIPlpiIsObjlimExc, SCIPlpiIsOptimal, TRUE, XPRS_LP_OPTIMAL_SCALEDINFEAS.
SCIP_Bool SCIPlpiIsObjlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the objective limit was reached
References FALSE, NULL, SCIPdebugMessage, TRUE.
Referenced by SCIPlpiIsOptimal, SCIPlpiIsStable, SCIPlpiSolveDual.
SCIP_Bool SCIPlpiIsIterlimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the iteration limit was reached
References ABORT_ZERO, FALSE, NULL, SCIPdebugMessage, TRUE.
SCIP_Bool SCIPlpiIsTimelimExc(SCIP_LPI *lpi)
LP interface structure
returns TRUE iff the time limit was reached
References ABORT_ZERO, FALSE, NULL, SCIPdebugMessage, TRUE.
int SCIPlpiGetInternalStatus(SCIP_LPI *lpi)
LP interface structure
returns the internal solution status of the solver
References FALSE, NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiIgnoreInstability(SCIP_LPI *lpi, SCIP_Bool *success)
LP interface structure
tries to reset the internal status of the LP solver in order to ignore an instability of the last solving call
References FALSE, NULL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiGetObjval(SCIP_LPI *lpi, SCIP_Real *objval)
LP interface structure
gets objective value of solutiongets objective value of solutionif the solution status is iteration limit reached (GRB_ITERATION_LIMIT), the objective value was not computed
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPlpiInfinity.
Referenced by SCIPlpiSolveDual.
SCIP_RETCODE SCIPlpiGetSol(SCIP_LPI *lpi, SCIP_Real *objval, SCIP_Real *primsol, SCIP_Real *dualsol, SCIP_Real *activity, SCIP_Real *redcost)
LP interface structure
gets primal and dual solution vectors for feasible LPsgets primal and dual solution vectors
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_CALL, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetPrimalRay(SCIP_LPI *lpi, SCIP_Real *ray)
LP interface structure
gets primal ray for unbounded LPs
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetDualfarkas(SCIP_LPI *lpi, SCIP_Real *dualfarkas)
LP interface structure
gets dual Farkas proof for infeasibilitygets dual farkas proof for infeasibility
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiGetIterations(SCIP_LPI *lpi, int *iterations)
LP interface structure
gets the number of LP iterations of the last solve call
References NULL, QS_CONDRET, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetRealSolQuality(SCIP_LPI *lpi, SCIP_LPSOLQUALITY qualityindicator, SCIP_Real *quality)
LP interface structure
gets information about the quality of an LP solutionSuch information is usually only available, if also a (maybe not optimal) solution is available. The LPI should return SCIP_INVALID for quality, if the requested quantity is not available.gets information about the quality of an LP solutionSuch information is usually only available, if also a (maybe not optimal) solution is available. The LPI should return SCIP_INVALID for quality, if the requested quality is not available.
References CHECK_ZERO, NULL, SCIP_INVALID, SCIP_INVALIDDATA, SCIP_LPSOLQUALITY_ESTIMCONDITION, SCIP_LPSOLQUALITY_EXACTCONDITION, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage.
Referenced by SCIPlpiIsStable.
SCIP_RETCODE SCIPlpiGetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
gets current basis status for columns and rows; arrays must be large enough to store the basis status
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage.
Referenced by SCIPlpiGetState.
SCIP_RETCODE SCIPlpiSetBase(SCIP_LPI *lpi, int *cstat, int *rstat)
LP interface structure
sets current basis status for columns and rows
References CHECK_ZERO, EPSEQ, FALSE, MOSEK_CALL, NULL, QS_RETURN, SCIP_ALLOC, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, SOPLEX_TRY.
Referenced by SCIPlpiSetState.
SCIP_RETCODE SCIPlpiGetBasisInd(SCIP_LPI *lpi, int *bind)
LP interface structure
returns the indices of the basic columns and rows; basic column n gives value n, basic row m gives value -1-m
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_CALL_QUIET, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
Referenced by SCIPlpiGetBInvRow.
SCIP_RETCODE SCIPlpiGetBInvRow(SCIP_LPI *lpi, int r, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_ALLOC, SCIP_CALL, SCIP_CALL_QUIET, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPlpiGetBasisInd, SCIPmessagePrintWarning, SVECTOR.
Referenced by SCIPlpiGetBInvARow.
SCIP_RETCODE SCIPlpiGetBInvCol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix B^-1The LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_ALLOC, SCIP_CALL, SCIP_CALL_QUIET, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPerrorMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetBInvARow(SCIP_LPI *lpi, int r, const SCIP_Real *binvrow, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense row of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, MOSEK_CALL, NULL, QS_CONDRET, SCIP_ALLOC, SCIP_CALL, SCIP_CALL_QUIET, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, SCIPlpiGetBInvRow, SVECTOR.
SCIP_RETCODE SCIPlpiGetBInvACol(SCIP_LPI *lpi, int c, SCIP_Real *coef, int *inds, int *ninds)
LP interface structure
get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get column of inverse basis matrix times constraint matrix B^-1 * Aget dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h. get dense column of inverse basis matrix times constraint matrix B^-1 * AThe LP interface defines slack variables to have coefficient +1. This means that if, internally, the LP solver uses a -1 coefficient, then rows associated with slacks variables whose coefficient is -1, should be negated; see also the explanation in lpi.h.
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_ALLOC, SCIP_CALL, SCIP_CALL_QUIET, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPdebugMessage, SCIPerrorMessage, SVECTOR.
SCIP_RETCODE SCIPlpiGetState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
stores LPi state (like basis information) into lpistate objectstores LP state (like basis information) into lpistate object
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_ALLOC, SCIP_Bool, SCIP_CALL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage, SCIPlpiExistsDualRay, SCIPlpiGetBase.
SCIP_RETCODE SCIPlpiSetState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE *lpistate)
LP interface structure
loads LPi state (like basis information) into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetState()
References CHECK_ZERO, FALSE, MOSEK_CALL, NULL, QS_RETURN, REALABS, SCIP_BASESTAT_BASIC, SCIP_BASESTAT_LOWER, SCIP_BASESTAT_UPPER, SCIP_BASESTAT_ZERO, SCIP_CALL, SCIP_INVALIDDATA, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_Real, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, SCIPlpiIsInfinity, SCIPlpiSetBase.
SCIP_RETCODE SCIPlpiClearState(SCIP_LPI *lpi)
LP interface structure
clears current LPi state (like basis information) of the solver
References CHECK_ZERO, NULL, SCIP_LPERROR, SCIP_OKAY, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning, TRUE.
SCIP_RETCODE SCIPlpiFreeState(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPISTATE **lpistate)
LP interface structure
frees LPi state informationfrees LP state information
References NULL, SCIP_OKAY, SCIPdebugMessage.
SCIP_Bool SCIPlpiHasStateBasis(SCIP_LPI *lpi, SCIP_LPISTATE *lpistate)
LP interface structure
checks, whether the given LPi state contains simplex basis informationchecks, whether the given LP state contains simplex basis information
References FALSE, NULL, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiReadState(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LPi state (like basis information from a filereads LP state (like basis information) from a filereads LP state (like basis information from a file
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_LPERROR, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_READERROR, SCIPdebugMessage, SCIPerrorMessage, SOPLEX_TRY.
SCIP_RETCODE SCIPlpiWriteState(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LPi state (like basis information) to a filewrites LP state (like basis information) to a file
References CHECK_ZERO, MOSEK_CALL, NULL, QS_ERROR, SCIP_LPERROR, SCIP_MAXSTRLEN, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_WRITEERROR, SCIPdebugMessage, SCIPerrorMessage, SOPLEX_TRY.
Referenced by SCIPlpiSolveDual, SCIPlpiSolvePrimal.
SCIP_RETCODE SCIPlpiGetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
stores LPi pricing norms into lpinorms objectstores LPi pricing norms information stores LPi pricing norms informationstores LPi pricing norms information stores LPi pricing norms information stores LPi pricing norms information stores LPi pricing norms information stores LPi pricing norms information stores LPi pricing norms information stores LPi pricing norms information
References CHECK_ZERO, NULL, SCIP_ALLOC, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiSetNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS *lpinorms)
LP interface structure
loads LPi pricing norms into solver; note that the LP might have been extended with additional columns and rows since the norms were stored with SCIPlpiGetNorms()loads LPi pricing norms into solver; note that the LP might have been extended with additional columns and rows since the state was stored with SCIPlpiGetNorms()
References CHECK_ZERO, SCIP_LPiNorms::head, SCIP_LPiNorms::ncols, SCIP_LPiNorms::norm, SCIP_LPiNorms::normlen, SCIP_LPiNorms::norms, SCIP_LPiNorms::nrows, NULL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiFreeNorms(SCIP_LPI *lpi, BMS_BLKMEM *blkmem, SCIP_LPINORMS **lpinorms)
LP interface structure
frees LPi pricing norms informationfrees pricing norms information
References NULL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIPdebugMessage.
SCIP_RETCODE SCIPlpiGetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int *ival)
LP interface structure
gets integer parameter of LP
References CHECK_ZERO, CPX_INT_MAX, FALSE, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_LPPAR_FASTMIP, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_LPPAR_THREADS, SCIP_LPPAR_TIMING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIP_PRICING_AUTO, SCIP_PRICING_DEVEX, SCIP_PRICING_FULL, SCIP_PRICING_PARTIAL, SCIP_PRICING_STEEP, SCIP_PRICING_STEEPQSTART, SCIP_Real, SCIPdebugMessage, TRUE.
SCIP_RETCODE SCIPlpiSetIntpar(SCIP_LPI *lpi, SCIP_LPPARAM type, int ival)
LP interface structure
sets integer parameter of LP
References CHECK_ZERO, CPX_INT_MAX, FALSE, MIN, MOSEK_CALL, NULL, QS_RETURN, SCIP_Bool, SCIP_CALL, SCIP_INVALIDDATA, SCIP_LPERROR, SCIP_LPPAR_FASTMIP, SCIP_LPPAR_FROMSCRATCH, SCIP_LPPAR_LPINFO, SCIP_LPPAR_LPITLIM, SCIP_LPPAR_PRESOLVING, SCIP_LPPAR_PRICING, SCIP_LPPAR_SCALING, SCIP_LPPAR_THREADS, SCIP_LPPAR_TIMING, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIP_PRICING_AUTO, SCIP_PRICING_DEVEX, SCIP_PRICING_FULL, SCIP_PRICING_LPIDEFAULT, SCIP_PRICING_PARTIAL, SCIP_PRICING_STEEP, SCIP_PRICING_STEEPQSTART, SCIPABORT, SCIPdebugMessage, SCIPerrorMessage, TRUE.
Referenced by SCIPlpiAddRows, SCIPlpiCreate.
SCIP_RETCODE SCIPlpiGetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real *dval)
LP interface structure
gets floating point parameter of LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_LPPAR_BARRIERCONVTOL, SCIP_LPPAR_CONDITIONLIMIT, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_MARKOWITZ, SCIP_LPPAR_ROWREPSWITCH, SCIP_LPPAR_UOBJLIM, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage, SCIPlpiInfinity.
SCIP_RETCODE SCIPlpiSetRealpar(SCIP_LPI *lpi, SCIP_LPPARAM type, SCIP_Real dval)
LP interface structure
sets floating point parameter of LP
References CHECK_ZERO, MOSEK_CALL, NULL, QS_RETURN, SCIP_CALL, SCIP_LPPAR_BARRIERCONVTOL, SCIP_LPPAR_CONDITIONLIMIT, SCIP_LPPAR_DUALFEASTOL, SCIP_LPPAR_FEASTOL, SCIP_LPPAR_LOBJLIM, SCIP_LPPAR_LPTILIM, SCIP_LPPAR_MARKOWITZ, SCIP_LPPAR_ROWREPSWITCH, SCIP_LPPAR_UOBJLIM, SCIP_OBJSEN_MAXIMIZE, SCIP_OBJSEN_MINIMIZE, SCIP_OKAY, SCIP_PARAMETERUNKNOWN, SCIPdebugMessage, SCIPlpiInfinity.
SCIP_Real SCIPlpiInfinity(SCIP_LPI *lpi)
LP interface structure
returns value treated as infinity in the LP solver
References LPIINFINITY, NULL, SCIPdebugMessage.
Referenced by SCIPlpiCreate, SCIPlpiGetObjval, SCIPlpiGetRealpar, SCIPlpiSetRealpar.
SCIP_Bool SCIPlpiIsInfinity(SCIP_LPI *lpi, SCIP_Real val)
LP interface structure
checks if given value is treated as infinity in the LP solver
References FALSE, IS_POSINF, LPIINFINITY, NULL, SCIPdebugMessage, TRUE.
Referenced by SCIPlpiSetState.
SCIP_RETCODE SCIPlpiReadLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
reads LP from a file
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_NOFILE, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_READERROR, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning.
SCIP_RETCODE SCIPlpiWriteLP(SCIP_LPI *lpi, const char *fname)
LP interface structure
writes LP to a file
References CHECK_ZERO, MOSEK_CALL, NULL, SCIP_OKAY, SCIP_PLUGINNOTFOUND, SCIP_READERROR, SCIP_WRITEERROR, SCIPdebugMessage, SCIPerrorMessage, SCIPmessagePrintWarning.
Referenced by SCIPlpiSolveDual, SCIPlpiSolvePrimal.