pub_expr.h
SCIP_EXPRCURV SCIPexprcurvAdd(SCIP_EXPRCURV curv1, SCIP_EXPRCURV curv2)
curvature of first summand
gives curvature for a sum of two functions with given curvature
SCIP_EXPRCURV SCIPexprcurvNegate(SCIP_EXPRCURV curvature)
curvature of function
gives the curvature for the negation of a function with given curvature
SCIP_EXPRCURV SCIPexprcurvMultiply(SCIP_Real factor, SCIP_EXPRCURV curvature)
constant factor
gives curvature for a functions with given curvature multiplied by a constant factor
SCIP_EXPRCURV SCIPexprcurvPower(SCIP_INTERVAL basebounds, SCIP_EXPRCURV basecurv, SCIP_Real exponent)
bounds on base function
gives curvature for base^exponent for given bounds and curvature of base-function and constant exponent
SCIP_EXPRCURV SCIPexprcurvMonomial(int nfactors, SCIP_Real *exponents, int *factoridxs, SCIP_EXPRCURV *factorcurv, SCIP_INTERVAL *factorbounds)
number of factors in monomial
gives curvature for a monomial with given curvatures and bounds for each factor
const char* SCIPexprcurvGetName(SCIP_EXPRCURV curv)
curvature
gives name as string for a curvature
const char* SCIPexpropGetName(SCIP_EXPROP op)
expression operand
gives the name of an operand
int SCIPexpropGetNChildren(SCIP_EXPROP op)
expression operand
gives the number of children of a simple operand -1 for invalid operands and -2 for complex operands (those where the number of children depends on the expression)
SCIP_EXPROP SCIPexprGetOperator(SCIP_EXPR *expr)
expression
gives operator of expression
int SCIPexprGetNChildren(SCIP_EXPR *expr)
expression
gives number of children of an expression
SCIP_EXPR** SCIPexprGetChildren(SCIP_EXPR *expr)
expression
gives pointer to array with children of an expression
int SCIPexprGetOpIndex(SCIP_EXPR *expr)
expression
gives index belonging to a SCIP_EXPR_VARIDX or SCIP_EXPR_PARAM operand
SCIP_Real SCIPexprGetOpReal(SCIP_EXPR *expr)
expression
gives real belonging to a SCIP_EXPR_CONST operand
void* SCIPexprGetOpData(SCIP_EXPR *expr)
expression
gives void* belonging to a complex operand
SCIP_Real SCIPexprGetRealPowerExponent(SCIP_EXPR *expr)
expression
gives exponent belonging to a SCIP_EXPR_REALPOWER expression
int SCIPexprGetIntPowerExponent(SCIP_EXPR *expr)
expression
gives exponent belonging to a SCIP_EXPR_INTPOWER expression
SCIP_Real SCIPexprGetSignPowerExponent(SCIP_EXPR *expr)
expression
gives exponent belonging to a SCIP_EXPR_SIGNPOWER expression
SCIP_Real* SCIPexprGetLinearCoefs(SCIP_EXPR *expr)
expression
gives linear coefficients belonging to a SCIP_EXPR_LINEAR expression
SCIP_Real SCIPexprGetLinearConstant(SCIP_EXPR *expr)
expression
gives constant belonging to a SCIP_EXPR_LINEAR expression
SCIP_QUADELEM* SCIPexprGetQuadElements(SCIP_EXPR *expr)
quadratic expression
gives quadratic elements belonging to a SCIP_EXPR_QUADRATIC expression
SCIP_Real SCIPexprGetQuadConstant(SCIP_EXPR *expr)
quadratic expression
gives constant belonging to a SCIP_EXPR_QUADRATIC expression
SCIP_Real* SCIPexprGetQuadLinearCoefs(SCIP_EXPR *expr)
quadratic expression
gives linear coefficients belonging to a SCIP_EXPR_QUADRATIC expression can be NULL if all coefficients are 0.0
int SCIPexprGetNQuadElements(SCIP_EXPR *expr)
quadratic expression
gives number of quadratic elements belonging to a SCIP_EXPR_QUADRATIC expression
SCIP_EXPRDATA_MONOMIAL** SCIPexprGetMonomials(SCIP_EXPR *expr)
expression
gives the monomials belonging to a SCIP_EXPR_POLYNOMIAL expression
int SCIPexprGetNMonomials(SCIP_EXPR *expr)
expression
gives the number of monomials belonging to a SCIP_EXPR_POLYNOMIAL expression
SCIP_Real SCIPexprGetPolynomialConstant(SCIP_EXPR *expr)
expression
gives the constant belonging to a SCIP_EXPR_POLYNOMIAL expression
SCIP_Real SCIPexprGetMonomialCoef(SCIP_EXPRDATA_MONOMIAL *monomial)
monomial
gets coefficient of a monomial
int SCIPexprGetMonomialNFactors(SCIP_EXPRDATA_MONOMIAL *monomial)
monomial
gets number of factors of a monomial
int* SCIPexprGetMonomialChildIndices(SCIP_EXPRDATA_MONOMIAL *monomial)
monomial
gets indices of children corresponding to factors of a monomial
SCIP_Real* SCIPexprGetMonomialExponents(SCIP_EXPRDATA_MONOMIAL *monomial)
monomial
gets exponents in factors of a monomial
SCIP_USEREXPRDATA* SCIPexprGetUserData(SCIP_EXPR *expr)
gets user data of a user expression
SCIP_Bool SCIPexprHasUserEstimator(SCIP_EXPR *expr)
indicates whether a user expression has the estimator callback defined
SCIP_EXPRINTCAPABILITY SCIPexprGetUserEvalCapability(SCIP_EXPR *expr)
gives the evaluation capability of a user expression
SCIP_RETCODE SCIPexprCreate(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, SCIP_EXPROP op,...)
block memory data structure
creates a simple expression
SCIP_RETCODE SCIPexprCopyDeep(BMS_BLKMEM *blkmem, SCIP_EXPR **targetexpr, SCIP_EXPR *sourceexpr)
block memory data structure
copies an expression including its children
Referenced by SCIPexprintCompile.
void SCIPexprFreeDeep(BMS_BLKMEM *blkmem, SCIP_EXPR **expr)
block memory data structure
frees an expression including its children
Referenced by SCIPexprintCompile, SCIPexprintFreeData.
void SCIPexprFreeShallow(BMS_BLKMEM *blkmem, SCIP_EXPR **expr)
block memory data structure
frees an expression but not its children
SCIP_RETCODE SCIPexprAdd(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, SCIP_Real coef1, SCIP_EXPR *term1, SCIP_Real coef2, SCIP_EXPR *term2, SCIP_Real constant)
block memory data structure
creates an expression from the addition of two given expression, with coefficients, and a constantthe given expressions may be modified or freed, otherwise it will be used a child expression favors creation and maintaining of SCIP_EXPR_LINEAR over SCIP_EXPR_PLUS or SCIP_EXPR_SUM
SCIP_RETCODE SCIPexprMulConstant(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, SCIP_EXPR *term, SCIP_Real factor)
block memory data structure
creates an expression from the multiplication of an expression with a constantthe given expressions may be modified or freed, otherwise it will be used a child expression favors creation of SCIP_EXPR_LINEAR over SCIP_EXPR_MUP or SCIP_EXPR_PROD
SCIP_RETCODE SCIPexprCreateLinear(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, int nchildren, SCIP_EXPR **children, SCIP_Real *coefs, SCIP_Real constant)
block memory data structure
creates a SCIP_EXPR_LINEAR expression that is (affine) linear in its children: constant + sum_i coef_i child_i
SCIP_RETCODE SCIPexprAddToLinear(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, int nchildren, SCIP_Real *coefs, SCIP_EXPR **children, SCIP_Real constant)
block memory
adds new terms to a linear expression
SCIP_RETCODE SCIPexprCreateQuadratic(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, int nchildren, SCIP_EXPR **children, SCIP_Real constant, SCIP_Real *lincoefs, int nquadelems, SCIP_QUADELEM *quadelems)
block memory data structure
creates a SCIP_EXPR_QUADRATIC expression: constant + sum_i coef_i child_i + sum_i coef_i child1_i child2_i
void SCIPexprSortQuadElems(SCIP_EXPR *expr)
quadratic expression
ensures that quadratic elements of a quadratic expression are sorted
SCIP_RETCODE SCIPexprCreatePolynomial(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, int nchildren, SCIP_EXPR **children, int nmonomials, SCIP_EXPRDATA_MONOMIAL **monomials, SCIP_Real constant, SCIP_Bool copymonomials)
block memory data structure
creates a SCIP_EXPR_POLYNOMIAL expression from an array of monomials: constant + sum_i monomial_i
SCIP_RETCODE SCIPexprAddMonomials(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, int nmonomials, SCIP_EXPRDATA_MONOMIAL **monomials, SCIP_Bool copymonomials)
block memory of expression
adds an array of monomials to a SCIP_EXPR_POLYNOMIAL expression
void SCIPexprChgPolynomialConstant(SCIP_EXPR *expr, SCIP_Real constant)
expression
changes the constant in a SCIP_EXPR_POLYNOMIAL expression
void SCIPexprMultiplyPolynomialByConstant(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, SCIP_Real factor)
block memory
multiplies each summand of a polynomial by a given constant
SCIP_RETCODE SCIPexprMultiplyPolynomialByMonomial(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, SCIP_EXPRDATA_MONOMIAL *factor, int *childmap)
block memory
multiplies each summand of a polynomial by a given monomial
SCIP_RETCODE SCIPexprMultiplyPolynomialByPolynomial(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, SCIP_EXPR *factor, int *childmap)
block memory
multiplies this polynomial by a polynomial factor needs to be different from expr
SCIP_RETCODE SCIPexprPolynomialPower(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, int exponent)
block memory
takes a power of the polynomial exponent need to be an integer polynomial need to be a monomial, if exponent is negative
void SCIPexprMergeMonomials(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, SCIP_Real eps, SCIP_Bool mergefactors)
block memory
merges monomials in a polynomial expression that differ only in coefficient into a single monomial eliminates monomials with coefficient between -eps and eps
SCIP_RETCODE SCIPexprCreateMonomial(BMS_BLKMEM *blkmem, SCIP_EXPRDATA_MONOMIAL **monomial, SCIP_Real coef, int nfactors, int *childidxs, SCIP_Real *exponents)
block memory
creates a monomial
void SCIPexprFreeMonomial(BMS_BLKMEM *blkmem, SCIP_EXPRDATA_MONOMIAL **monomial)
block memory
frees a monomial
void SCIPexprSortMonomialFactors(SCIP_EXPRDATA_MONOMIAL *monomial)
monomial
ensures that factors in a monomial are sorted
SCIP_Bool SCIPexprFindMonomialFactor(SCIP_EXPRDATA_MONOMIAL *monomial, int childidx, int *pos)
monomial
finds a factor corresponding to a given child index in a monomial note that if the factors have not been merged, the position of some factor corresponding to a given child is given returns TRUE if a factor is found, FALSE if not
SCIP_Bool SCIPexprAreMonomialsEqual(SCIP_EXPRDATA_MONOMIAL *monomial1, SCIP_EXPRDATA_MONOMIAL *monomial2, SCIP_Real eps)
first monomial
checks if two monomials are equal
SCIP_RETCODE SCIPexprAddMonomialFactors(BMS_BLKMEM *blkmem, SCIP_EXPRDATA_MONOMIAL *monomial, int nfactors, int *childidxs, SCIP_Real *exponents)
block memory
adds factors to a monomial
void SCIPexprChgMonomialCoef(SCIP_EXPRDATA_MONOMIAL *monomial, SCIP_Real newcoef)
monomial
changes coefficient of monomial
SCIP_RETCODE SCIPexprMultiplyMonomialByMonomial(BMS_BLKMEM *blkmem, SCIP_EXPRDATA_MONOMIAL *monomial, SCIP_EXPRDATA_MONOMIAL *factor, int *childmap)
block memory
multiplies a monomial with a monomial
void SCIPexprMonomialPower(SCIP_EXPRDATA_MONOMIAL *monomial, int exponent)
monomial
replaces the monomial by a power of the monomial allows only integers as exponent
void SCIPexprMergeMonomialFactors(SCIP_EXPRDATA_MONOMIAL *monomial, SCIP_Real eps)
monomial
merges factors that correspond to the same child by adding exponents eliminates factors with exponent between -eps and eps
void SCIPexprSortMonomials(SCIP_EXPR *expr)
polynomial expression
ensures that monomials of a polynomial are sorted
SCIP_RETCODE SCIPexprCreateUser(BMS_BLKMEM *blkmem, SCIP_EXPR **expr, int nchildren, SCIP_EXPR **children, SCIP_USEREXPRDATA *data, SCIP_EXPRINTCAPABILITY evalcapability, SCIP_DECL_USEREXPREVAL((*eval)), SCIP_DECL_USEREXPRINTEVAL((*inteval)), SCIP_DECL_USEREXPRCURV((*curv)), SCIP_DECL_USEREXPRPROP((*prop)), SCIP_DECL_USEREXPRESTIMATE((*estimate)), SCIP_DECL_USEREXPRCOPYDATA((*copydata)), SCIP_DECL_USEREXPRFREEDATA((*freedata)))
block memory data structure
creates a user expression
SCIP_Bool SCIPexprHasParam(SCIP_EXPR *expr)
expression
indicates whether the expression contains a SCIP_EXPR_PARAM
SCIP_RETCODE SCIPexprGetMaxDegree(SCIP_EXPR *expr, int *maxdegree)
expression
gets maximal degree of expression, or SCIP_EXPR_DEGREEINFINITY if not a polynomial
void SCIPexprGetVarsUsage(SCIP_EXPR *expr, int *varsusage)
expression to update
counts usage of variables in expression
SCIP_Bool SCIPexprAreEqual(SCIP_EXPR *expr1, SCIP_EXPR *expr2, SCIP_Real eps)
first expression
compares whether two expressions are the same inconclusive, i.e., may give FALSE even if expressions are equivalent (x*y != y*x)
SCIP_RETCODE SCIPexprSimplify(BMS_BLKMEM *blkmem, SCIP_MESSAGEHDLR *messagehdlr, SCIP_EXPR *expr, SCIP_Real eps, int maxexpansionexponent, int nvars, int *nlinvars, int *linidxs, SCIP_Real *lincoefs)
block memory data structure
aims at simplifying an expression and splitting of a linear expression if linear variables are split off, expression interpreter data, if stored in the tree, is freed
SCIP_RETCODE SCIPexprEvalShallow(SCIP_EXPR *expr, SCIP_Real *argvals, SCIP_Real *varvals, SCIP_Real *param, SCIP_Real *val)
expression
evaluates an expression w.r.t. given values for children expressions
SCIP_RETCODE SCIPexprEval(SCIP_EXPR *expr, SCIP_Real *varvals, SCIP_Real *param, SCIP_Real *val)
expression
evaluates an expression w.r.t. a point
SCIP_RETCODE SCIPexprEvalIntShallow(SCIP_EXPR *expr, SCIP_Real infinity, SCIP_INTERVAL *argvals, SCIP_INTERVAL *varvals, SCIP_Real *param, SCIP_INTERVAL *val)
expression
evaluates an expression w.r.t. given interval values for children expressions
SCIP_RETCODE SCIPexprEvalInt(SCIP_EXPR *expr, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_Real *param, SCIP_INTERVAL *val)
expression
evaluates an expression w.r.t. an interval
SCIP_RETCODE SCIPexprEvalUser(SCIP_EXPR *expr, SCIP_Real *argvals, SCIP_Real *val, SCIP_Real *gradient, SCIP_Real *hessian)
expression
evaluates a user expression w.r.t. given values for children expressions
Referenced by exprEvalUser.
SCIP_RETCODE SCIPexprEvalIntUser(SCIP_EXPR *expr, SCIP_Real infinity, SCIP_INTERVAL *argvals, SCIP_INTERVAL *val, SCIP_INTERVAL *gradient, SCIP_INTERVAL *hessian)
expression
evaluates a user expression w.r.t. an interval
Referenced by exprEvalUser.
SCIP_RETCODE SCIPexprCheckCurvature(SCIP_EXPR *expr, SCIP_Real infinity, SCIP_INTERVAL *varbounds, SCIP_Real *param, SCIP_EXPRCURV *curv, SCIP_INTERVAL *bounds)
expression to check
tries to determine the curvature type of an expression w.r.t. given variable domains
SCIP_RETCODE SCIPexprEstimateUser(SCIP_EXPR *expr, SCIP_Real infinity, SCIP_Real *argvals, SCIP_INTERVAL *argbounds, SCIP_Bool overestimate, SCIP_Real *coeffs, SCIP_Real *constant, SCIP_Bool *success)
expression
under-/overestimates a user expression w.r.t. to given values and bounds for children expressions
SCIP_RETCODE SCIPexprSubstituteVars(BMS_BLKMEM *blkmem, SCIP_EXPR *expr, SCIP_EXPR **substexprs)
block memory data structure
substitutes variables (SCIP_EXPR_VARIDX) by expressions Note that only the children of the given expr are checked! A variable with index i is replaced by a copy of substexprs[i], if that latter is not NULL if substexprs[i] == NULL, then the variable expression i is not touched
void SCIPexprReindexVars(SCIP_EXPR *expr, int *newindices)
expression to update
updates variable indices in expression tree
void SCIPexprReindexParams(SCIP_EXPR *expr, int *newindices)
expression to update
updates parameter indices in expression tree
void SCIPexprPrint(SCIP_EXPR *expr, SCIP_MESSAGEHDLR *messagehdlr, FILE *file, const char **varnames, const char **paramnames, SCIP_Real *paramvals)
expression
prints an expression
SCIP_RETCODE SCIPexprParse(BMS_BLKMEM *blkmem, SCIP_MESSAGEHDLR *messagehdlr, SCIP_EXPR **expr, const char *str, const char *lastchar, int *nvars, int *varnames)
block memory data structure
parses an expression from a string
SCIP_EXPR* SCIPexprtreeGetRoot(SCIP_EXPRTREE *tree)
expression tree
returns root expression of an expression tree
Referenced by SCIPexprintCompile, SCIPexprintEval, SCIPexprintEvalInt.
int SCIPexprtreeGetNVars(SCIP_EXPRTREE *tree)
expression tree
returns number of variables in expression tree
Referenced by SCIPexprintCompile, SCIPexprintEval, SCIPexprintEvalInt, SCIPexprintGrad, SCIPexprintGradInt, SCIPexprintHessianDense, SCIPexprintHessianSparsityDense.
int SCIPexprtreeGetNParams(SCIP_EXPRTREE *tree)
expression tree
returns number of parameters in expression tree
SCIP_Real* SCIPexprtreeGetParamVals(SCIP_EXPRTREE *tree)
expression tree
returns values of parameters or NULL if none
Referenced by SCIPexprintEval, SCIPexprintEvalInt.
void SCIPexprtreeSetParamVal(SCIP_EXPRTREE *tree, int paramidx, SCIP_Real paramval)
expression tree
sets value of a single parameter in expression tree
SCIP_EXPRINTDATA* SCIPexprtreeGetInterpreterData(SCIP_EXPRTREE *tree)
expression tree
gets data of expression tree interpreter, or NULL if not set
Referenced by SCIPexprintCompile, SCIPexprintEval, SCIPexprintEvalInt, SCIPexprintGetExprtreeCapability, SCIPexprintGrad, SCIPexprintGradInt, SCIPexprintHessianDense, SCIPexprintHessianSparsityDense, SCIPexprintNewParametrization.
void SCIPexprtreeSetInterpreterData(SCIP_EXPRTREE *tree, SCIP_EXPRINTDATA *interpreterdata)
expression tree
sets data of expression tree interpreter
Referenced by SCIPexprintCompile.
SCIP_RETCODE SCIPexprtreeFreeInterpreterData(SCIP_EXPRTREE *tree)
expression tree
frees data of expression tree interpreter, if any
SCIP_Bool SCIPexprtreeHasParam(SCIP_EXPRTREE *tree)
expression tree
indicates whether there are parameterized constants (SCIP_EXPR_PARAM) in expression tree
SCIP_RETCODE SCIPexprtreeGetMaxDegree(SCIP_EXPRTREE *tree, int *maxdegree)
expression tree
Gives maximal degree of expression in expression tree. If constant expression, gives 0, if linear expression, gives 1, if polynomial expression, gives its maximal degree, otherwise (nonpolynomial nonconstant expressions) gives at least SCIP_EXPR_DEGREEINFINITY.
SCIP_RETCODE SCIPexprtreeEval(SCIP_EXPRTREE *tree, SCIP_Real *varvals, SCIP_Real *val)
expression tree
evaluates an expression tree w.r.t. a point
Referenced by SCIPexprintEval.
SCIP_RETCODE SCIPexprtreeEvalInt(SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varvals, SCIP_INTERVAL *val)
expression tree
evaluates an expression tree w.r.t. an interval
Referenced by SCIPexprintEvalInt.
void SCIPexprtreePrint(SCIP_EXPRTREE *tree, SCIP_MESSAGEHDLR *messagehdlr, FILE *file, const char **varnames, const char **paramnames)
expression tree
prints an expression tree
SCIP_RETCODE SCIPexprtreeCreate(BMS_BLKMEM *blkmem, SCIP_EXPRTREE **tree, SCIP_EXPR *root, int nvars, int nparams, SCIP_Real *params)
block memory data structure
creates an expression tree
SCIP_RETCODE SCIPexprtreeCopy(BMS_BLKMEM *blkmem, SCIP_EXPRTREE **targettree, SCIP_EXPRTREE *sourcetree)
block memory that should be used in new expression tree
copies an expression tree
SCIP_RETCODE SCIPexprtreeFree(SCIP_EXPRTREE **tree)
pointer to expression tree that is freed
frees an expression tree
SCIP_RETCODE SCIPexprtreeSetParams(SCIP_EXPRTREE *tree, int nparams, SCIP_Real *paramvals)
expression tree
sets number and values of all parameters in expression tree
void SCIPexprtreeGetVarsUsage(SCIP_EXPRTREE *tree, int *varsusage)
expression tree
gives the number of usages for each variable in the expression tree
SCIP_RETCODE SCIPexprtreeSimplify(SCIP_EXPRTREE *tree, SCIP_MESSAGEHDLR *messagehdlr, SCIP_Real eps, int maxexpansionexponent, int *nlinvars, int *linidxs, SCIP_Real *lincoefs)
expression tree
aims at simplifying an expression and splitting of a linear expression if linear variables are split off, expression interpreter data, if stored in the tree, is freed
SCIP_RETCODE SCIPexprtreeAddExpr(SCIP_EXPRTREE *tree, SCIP_EXPR *expr, SCIP_Bool copyexpr)
expression tree
adds an expression to the root expression of the tree the root is replaced with an SCIP_EXPR_PLUS expression which has the previous root and the given expression as children
SCIP_RETCODE SCIPexprtreeCheckCurvature(SCIP_EXPRTREE *tree, SCIP_Real infinity, SCIP_INTERVAL *varbounds, SCIP_EXPRCURV *curv, SCIP_INTERVAL *bounds)
expression tree
tries to determine the curvature type of an expression tree w.r.t. given variable domains
SCIP_RETCODE SCIPexprtreeSubstituteVars(SCIP_EXPRTREE *tree, SCIP_EXPR **substexprs)
expression tree
substitutes variables (SCIP_EXPR_VARIDX) in an expression tree by expressions A variable with index i is replaced by a copy of substexprs[i], if that latter is not NULL if substexprs[i] == NULL, then the variable expression i is not touched
void SCIPquadelemSort(SCIP_QUADELEM *quadelems, int nquadelems)
array of quadratic elements
sorts an array of quadratic elements The elements are sorted such that the first index is increasing and such that among elements with the same first index, the second index is increasing. For elements with same first and second index, the order is not defined.
SCIP_Bool SCIPquadelemSortedFind(SCIP_QUADELEM *quadelems, int idx1, int idx2, int nquadelems, int *pos)
array of quadratic elements
Finds an index pair in a sorted array of quadratic elements. If (idx1,idx2) is found in quadelems, then returns TRUE and stores position of quadratic element in *pos. If (idx1,idx2) is not found in quadelems, then returns FALSE and stores position where a quadratic element with these indices would be inserted in *pos. Assumes that idx1 <= idx2.
void SCIPquadelemSqueeze(SCIP_QUADELEM *quadelems, int nquadelems, int *nquadelemsnew)
array of quadratic elements
Adds quadratic elements with same index and removes elements with coefficient 0.0. Assumes that elements have been sorted before.
void SCIPexprgraphCaptureNode(SCIP_EXPRGRAPHNODE *node)
expression graph node to capture
captures node, i.e., increases number of uses
SCIP_Bool SCIPexprgraphIsNodeEnabled(SCIP_EXPRGRAPHNODE *node)
expression graph node to enable
returns whether a node is currently enabled
int SCIPexprgraphGetNodeNChildren(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets number of children of a node in an expression graph
SCIP_EXPRGRAPHNODE** SCIPexprgraphGetNodeChildren(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets children of a node in an expression graph
int SCIPexprgraphGetNodeNParents(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets number of parents of a node in an expression graph
SCIP_EXPRGRAPHNODE** SCIPexprgraphGetNodeParents(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets parents of a node in an expression graph
int SCIPexprgraphGetNodeDepth(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets depth of node in expression graph
int SCIPexprgraphGetNodePosition(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets position of node in expression graph at its depth level
SCIP_EXPROP SCIPexprgraphGetNodeOperator(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets operator of a node in an expression graph
int SCIPexprgraphGetNodeOperatorIndex(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives index belonging to a SCIP_EXPR_VARIDX or SCIP_EXPR_PARAM operand
SCIP_Real SCIPexprgraphGetNodeOperatorReal(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives real belonging to a SCIP_EXPR_CONST operand
void* SCIPexprgraphGetNodeVar(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node)
expression graph
gives variable belonging to a SCIP_EXPR_VARIDX expression
SCIP_Real SCIPexprgraphGetNodeRealPowerExponent(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives exponent belonging to a SCIP_EXPR_REALPOWER expression
int SCIPexprgraphGetNodeIntPowerExponent(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives exponent belonging to a SCIP_EXPR_INTPOWER expression
SCIP_Real SCIPexprgraphGetNodeSignPowerExponent(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives exponent belonging to a SCIP_EXPR_SIGNPOWER expression
SCIP_Real* SCIPexprgraphGetNodeLinearCoefs(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives linear coefficients belonging to a SCIP_EXPR_LINEAR expression
SCIP_Real SCIPexprgraphGetNodeLinearConstant(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives constant belonging to a SCIP_EXPR_LINEAR expression
SCIP_Real SCIPexprgraphGetNodeQuadraticConstant(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives constant belonging to a SCIP_EXPR_QUADRATIC expression
SCIP_Real* SCIPexprgraphGetNodeQuadraticLinearCoefs(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives linear coefficients belonging to a SCIP_EXPR_QUADRATIC expression, or NULL if all coefficients are 0.0
SCIP_QUADELEM* SCIPexprgraphGetNodeQuadraticQuadElements(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives quadratic elements belonging to a SCIP_EXPR_QUADRATIC expression
int SCIPexprgraphGetNodeQuadraticNQuadElements(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives number of quadratic elements belonging to a SCIP_EXPR_QUADRATIC expression
SCIP_EXPRDATA_MONOMIAL** SCIPexprgraphGetNodePolynomialMonomials(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives the monomials belonging to a SCIP_EXPR_POLYNOMIAL expression
int SCIPexprgraphGetNodePolynomialNMonomials(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives the number of monomials belonging to a SCIP_EXPR_POLYNOMIAL expression
SCIP_Real SCIPexprgraphGetNodePolynomialConstant(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives the constant belonging to a SCIP_EXPR_POLYNOMIAL expression
SCIP_RETCODE SCIPexprgraphGetNodePolynomialMonomialCurvature(SCIP_EXPRGRAPHNODE *node, int monomialidx, SCIP_Real infinity, SCIP_EXPRCURV *curv)
expression graph node
gives the curvature of a single monomial belonging to a SCIP_EXPR_POLYNOMIAL expression
SCIP_USEREXPRDATA* SCIPexprgraphGetNodeUserData(SCIP_EXPRGRAPHNODE *node)
gives the user data belonging to a SCIP_EXPR_USER expression
SCIP_Bool SCIPexprgraphHasNodeUserEstimator(SCIP_EXPRGRAPHNODE *node)
indicates whether a user expression has the estimator callback defined
SCIP_INTERVAL SCIPexprgraphGetNodeBounds(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets bounds of a node in an expression graph
SCIP_Real SCIPexprgraphGetNodeVal(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets value of expression associated to node from last evaluation call
SCIP_EXPRCURV SCIPexprgraphGetNodeCurvature(SCIP_EXPRGRAPHNODE *node)
expression graph node
gets curvature of expression associated to node from last curvature check call
SCIP_RETCODE SCIPexprgraphCreateNode(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node, SCIP_EXPROP op,...)
block memory
creates an expression graph node
SCIP_RETCODE SCIPexprgraphCreateNodeLinear(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node, int ncoefs, SCIP_Real *coefs, SCIP_Real constant)
block memory
creates an expression graph node for a linear expression
SCIP_RETCODE SCIPexprgraphCreateNodeQuadratic(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node, int nchildren, SCIP_Real *lincoefs, int nquadelems, SCIP_QUADELEM *quadelems, SCIP_Real constant)
block memory
creates an expression graph node for a quadratic expression
SCIP_RETCODE SCIPexprgraphCreateNodePolynomial(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node, int nmonomials, SCIP_EXPRDATA_MONOMIAL **monomials, SCIP_Real constant, SCIP_Bool copymonomials)
block memory
creates an expression graph node for a polynomial expression
SCIP_RETCODE SCIPexprgraphNodePolynomialAddMonomials(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE *node, int nmonomials, SCIP_EXPRDATA_MONOMIAL **monomials, SCIP_Bool copymonomials)
block memory
adds monomials to an expression graph node that is a polynomial expression
SCIP_RETCODE SCIPexprgraphCreateNodeUser(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node, SCIP_USEREXPRDATA *data, SCIP_EXPRINTCAPABILITY evalcapability, SCIP_DECL_USEREXPREVAL((*eval)), SCIP_DECL_USEREXPRINTEVAL((*inteval)), SCIP_DECL_USEREXPRCURV((*curv)), SCIP_DECL_USEREXPRPROP((*prop)), SCIP_DECL_USEREXPRESTIMATE((*estimate)), SCIP_DECL_USEREXPRCOPYDATA((*copydata)), SCIP_DECL_USEREXPRFREEDATA((*freedata)))
block memory
creates an expression graph node for a user expression
SCIP_RETCODE SCIPexprgraphNodeSplitOffLinear(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE **node, int linvarssize, int *nlinvars, void **linvars, SCIP_Real *lincoefs, SCIP_Real *constant)
expression graph
given a node of an expression graph, splitup a linear part which variables are not used somewhere else in the same expression E.g., if the expression is 1 + x + y + y^2, one gets 1 + x and the node remains at y + y^2. If the node is a linear expression, it may be freed. If it is not linear, the node may change, i.e., the remaining nonlinear part may be stored in a new node. It is assumed that the user had captured the node. It is assumed that the expression graph has been simplified before.
SCIP_RETCODE SCIPexprgraphMoveNodeParents(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE **srcnode, SCIP_EXPRGRAPHNODE *targetnode)
expression graph
moves parents from a one node to another node in other words, replaces the child srcnode by targetnode in all parents of srcnode srcnode may be freed, if not captured it is assumes that targetnode represents the same expression as srcnode
SCIP_RETCODE SCIPexprgraphReleaseNode(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE **node)
expression graph
releases node, i.e., decreases number of uses node is freed if no parents and no other uses children are recursively released if they have no other parents nodes that are removed are also freed if node correspond to a variable, then the variable is removed from the expression graph similar for constants
void SCIPexprgraphFreeNode(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPHNODE **node)
block memory
frees a node of an expression graph
void SCIPexprgraphEnableNode(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node)
expression graph
enables a node and recursively all its children in an expression graph
void SCIPexprgraphDisableNode(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node)
expression graph
disables a node and recursively all children which have no enabled parents in an expression graph
SCIP_Bool SCIPexprgraphHasNodeSibling(SCIP_EXPRGRAPHNODE *node)
expression graph node
returns whether the node has siblings in the expression graph
SCIP_Bool SCIPexprgraphAreAllNodeChildrenVars(SCIP_EXPRGRAPHNODE *node)
expression graph node
returns whether all children of an expression graph node are variable nodes gives TRUE for nodes without children
SCIP_Bool SCIPexprgraphHasNodeNonlinearAncestor(SCIP_EXPRGRAPHNODE *node)
expression graph node
returns whether the node has an ancestor which has a nonlinear expression operand
void SCIPexprgraphPrintNode(SCIP_EXPRGRAPHNODE *node, SCIP_MESSAGEHDLR *messagehdlr, FILE *file)
expression graph node
prints an expression graph node
void SCIPexprgraphTightenNodeBounds(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node, SCIP_INTERVAL nodebounds, SCIP_Real minstrength, SCIP_Real infinity, SCIP_Bool *cutoff)
expression graph
tightens the bounds in a node of the graph preparation for reverse propagation sets bound status to SCIP_EXPRBOUNDSTATUS_TIGHTENEDBYPARENTRECENT if tightening is strong enough and not cutoff
SCIP_RETCODE SCIPexprgraphUpdateNodeBoundsCurvature(SCIP_EXPRGRAPHNODE *node, SCIP_Real infinity, SCIP_Real minstrength, SCIP_Bool clearreverseprop)
expression graph node
ensures that bounds and curvature information in a node is uptodate assumes that bounds and curvature in children are uptodate
int SCIPexprgraphGetDepth(SCIP_EXPRGRAPH *exprgraph)
expression graph
get current maximal depth of expression graph
int* SCIPexprgraphGetNNodes(SCIP_EXPRGRAPH *exprgraph)
expression graph
gets array with number of nodes at each depth of expression graph
SCIP_EXPRGRAPHNODE*** SCIPexprgraphGetNodes(SCIP_EXPRGRAPH *exprgraph)
expression graph
gets nodes of expression graph, one array per depth
int SCIPexprgraphGetNVars(SCIP_EXPRGRAPH *exprgraph)
pointer to expression graph that should be freed
gets number of variables in expression graph
void** SCIPexprgraphGetVars(SCIP_EXPRGRAPH *exprgraph)
pointer to expression graph that should be freed
gets array of variables in expression graph
SCIP_EXPRGRAPHNODE** SCIPexprgraphGetVarNodes(SCIP_EXPRGRAPH *exprgraph)
pointer to expression graph that should be freed
gets array of expression graph nodes corresponding to variables
void SCIPexprgraphSetVarNodeValue(SCIP_EXPRGRAPHNODE *varnode, SCIP_Real value)
expression graph node corresponding to variable
sets value for a single variable given as expression graph node
void SCIPexprgraphSetVarsBounds(SCIP_EXPRGRAPH *exprgraph, SCIP_INTERVAL *varbounds)
expression graph
sets bounds for variables
void SCIPexprgraphSetVarBounds(SCIP_EXPRGRAPH *exprgraph, void *var, SCIP_INTERVAL varbounds)
expression graph
sets bounds for a single variable
void SCIPexprgraphSetVarNodeBounds(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *varnode, SCIP_INTERVAL varbounds)
expression graph
sets bounds for a single variable given as expression graph node
void SCIPexprgraphSetVarNodeLb(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *varnode, SCIP_Real lb)
expression graph
sets lower bound for a single variable given as expression graph node
void SCIPexprgraphSetVarNodeUb(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *varnode, SCIP_Real ub)
expression graph
sets upper bound for a single variable given as expression graph node
SCIP_INTERVAL* SCIPexprgraphGetVarsBounds(SCIP_EXPRGRAPH *exprgraph)
expression graph
gets bounds that are stored for all variables
SCIP_RETCODE SCIPexprgraphCreate(BMS_BLKMEM *blkmem, SCIP_EXPRGRAPH **exprgraph, int varssizeinit, int depthinit, SCIP_DECL_EXPRGRAPHVARADDED((*exprgraphvaradded)), SCIP_DECL_EXPRGRAPHVARREMOVE((*exprgraphvarremove)), SCIP_DECL_EXPRGRAPHVARCHGIDX((*exprgraphvarchgidx)), void *userdata)
block memory
creates an empty expression graph
SCIP_RETCODE SCIPexprgraphFree(SCIP_EXPRGRAPH **exprgraph)
pointer to expression graph that should be freed
frees an expression graph
SCIP_RETCODE SCIPexprgraphAddNode(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node, int mindepth, int nchildren, SCIP_EXPRGRAPHNODE **children)
expression graph
adds an expression graph node to an expression graph expression graph assumes ownership of node children are notified about new parent depth will be chosen to be the maximum of mindepth and the depth of all children plus one
SCIP_RETCODE SCIPexprgraphAddVars(SCIP_EXPRGRAPH *exprgraph, int nvars, void **vars, SCIP_EXPRGRAPHNODE **varnodes)
expression graph
adds variables to an expression graph, if not existing yet also already existing nodes are enabled
SCIP_RETCODE SCIPexprgraphAddConst(SCIP_EXPRGRAPH *exprgraph, SCIP_Real constant, SCIP_EXPRGRAPHNODE **constnode)
expression graph
adds a constant to an expression graph, if not existing yet also already existing nodes are enabled
SCIP_RETCODE SCIPexprgraphAddExprtreeSum(SCIP_EXPRGRAPH *exprgraph, int nexprtrees, SCIP_EXPRTREE **exprtrees, SCIP_Real *coefs, SCIP_EXPRGRAPHNODE **rootnode, SCIP_Bool *rootnodeisnew)
expression graph
adds sum of expression trees into expression graph node will also be captured
SCIP_RETCODE SCIPexprgraphReplaceVarByLinearSum(SCIP_EXPRGRAPH *exprgraph, void *var, int ncoefs, SCIP_Real *coefs, void **vars, SCIP_Real constant)
expression graph
replaces variable in expression graph by a linear sum of variables variables will be added if not in the graph yet
SCIP_Bool SCIPexprgraphFindVarNode(SCIP_EXPRGRAPH *exprgraph, void *var, SCIP_EXPRGRAPHNODE **varnode)
expression graph
finds expression graph node corresponding to a variable
SCIP_Bool SCIPexprgraphFindConstNode(SCIP_EXPRGRAPH *exprgraph, SCIP_Real constant, SCIP_EXPRGRAPHNODE **constnode)
expression graph
finds expression graph node corresponding to a constant
SCIP_RETCODE SCIPexprgraphPrintDot(SCIP_EXPRGRAPH *exprgraph, SCIP_MESSAGEHDLR *messagehdlr, FILE *file, const char **varnames)
expression graph
prints an expression graph in dot format
SCIP_RETCODE SCIPexprgraphEval(SCIP_EXPRGRAPH *exprgraph, SCIP_Real *varvals)
expression graph
evaluates nodes of expression graph for given values of variables
SCIP_RETCODE SCIPexprgraphPropagateVarBounds(SCIP_EXPRGRAPH *exprgraph, SCIP_Real infinity, SCIP_Bool clearreverseprop, SCIP_Bool *domainerror)
expression graph
propagates bound changes in variables forward through the expression graph
void SCIPexprgraphPropagateNodeBounds(SCIP_EXPRGRAPH *exprgraph, SCIP_Real infinity, SCIP_Real minstrength, SCIP_Bool *cutoff)
expression graph
propagates bound changes in nodes backward through the graph new bounds are not stored in varbounds, but only in nodes corresponding to variables NOTE: it is assumed that SCIPexprgraphPropagateVarBounds was called before if variable bounds were relaxed
SCIP_RETCODE SCIPexprgraphCheckCurvature(SCIP_EXPRGRAPH *exprgraph, SCIP_Real infinity, SCIP_Bool clearreverseprop)
expression graph
updates curvature information in expression graph nodes w.r.t. currently stored variable bounds implies update of bounds in expression graph
SCIP_RETCODE SCIPexprgraphSimplify(SCIP_EXPRGRAPH *exprgraph, SCIP_MESSAGEHDLR *messagehdlr, SCIP_Real eps, int maxexpansionexponent, SCIP_Bool *havechange, SCIP_Bool *domainerror)
expression graph
aims at simplifying an expression graph a domain error can occur when variables were fixed to values for which a parent expression is not defined (e.g., 0^(-1) or log(-1))
SCIP_RETCODE SCIPexprgraphGetTree(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *rootnode, SCIP_EXPRTREE **exprtree)
expression graph
creates an expression tree from a given node in an expression graph
SCIP_RETCODE SCIPexprgraphGetSeparableTrees(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node, int exprtreessize, int *nexprtrees, SCIP_EXPRTREE **exprtrees, SCIP_Real *exprtreecoefs)
expression graph
creates a sum of expression trees with pairwise disjoint variables from a given node in an expression graph Giving SCIPexprgraphGetNodeNChildren() for exprtreesize is always sufficient.
void SCIPexprgraphGetSubtreeVarsUsage(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node, int *varsusage)
expression graph
returns how often expression graph variables are used in a subtree of the expression graph
int SCIPexprgraphGetSumTreesNSummands(SCIP_EXPRGRAPHNODE *node)
expression graph node
gives the number of summands which the expression of an expression graph node consists of
SCIP_RETCODE SCIPexprgraphGetSumTrees(SCIP_EXPRGRAPH *exprgraph, SCIP_EXPRGRAPHNODE *node, int exprtreessize, int *nexprtrees, SCIP_EXPRTREE **exprtrees, SCIP_Real *exprtreecoefs)
expression graph
creates a sum of expression trees, possibly sharing variables, from a given node in an expression graph